export { ScopeDockProvider, useScopeDockContext } from "./scope-dock-context"
export { ScopeDock } from "./scope-dock"
export { ScopeGreeting } from "./scope-greeting"
export { useScopeAcknowledge } from "./use-scope-acknowledge"
export type { ScopeDockConfig } from "./scope-docks"
