#!/usr/bin/env node
// Check Next.js `metadata` / `generateMetadata` title & description against
// SEO length guidance and known placeholder text. No deps. Node >= 18.
// Usage: node .claude/skills/portfolio-writing/scripts/check-seo.mjs [path]

import { readFileSync, readdirSync, statSync } from "node:fs";
import { join, extname, relative } from "node:path";

const root = process.argv[2] || "src";
const SKIP_DIRS = new Set(["node_modules", ".next", ".git"]);

// Google typically renders ~50-60 chars of a title and ~120-158 chars of
// a description before truncating. Ranges below are the practical target.
const TITLE_MIN = 15;
const TITLE_MAX = 60;
const DESC_MIN = 70;
const DESC_MAX = 160;

const PLACEHOLDERS = [
  "create next app",
  "generated by create next app",
  "lorem ipsum",
  "my app",
  "app description",
  "welcome to",
  "the best place for",
];

function walk(dir, files = []) {
  for (const entry of readdirSync(dir)) {
    if (SKIP_DIRS.has(entry)) continue;
    const full = join(dir, entry);
    const st = statSync(full);
    if (st.isDirectory()) walk(full, files);
    else if ([".tsx", ".ts"].includes(extname(entry))) files.push(full);
  }
  return files;
}

// Extract the balanced-brace object literal starting at the first `{`
// found at/after `fromIndex`.
function extractObjectLiteral(text, fromIndex) {
  const start = text.indexOf("{", fromIndex);
  if (start === -1) return null;
  let depth = 0;
  for (let i = start; i < text.length; i++) {
    if (text[i] === "{") depth++;
    else if (text[i] === "}") {
      depth--;
      if (depth === 0) return text.slice(start, i + 1);
    }
  }
  return null;
}

function extractField(obj, field) {
  // string form: title: "..."
  let m = obj.match(new RegExp(`\\b${field}\\s*:\\s*(['"\`])((?:(?!\\1).)*)\\1`));
  if (m) return m[2];
  // object form: title: { default: "...", ... }
  const objMatch = obj.match(new RegExp(`\\b${field}\\s*:\\s*{([^}]*)}`));
  if (objMatch) {
    const inner = objMatch[1];
    const d = inner.match(/\bdefault\s*:\s*(['"`])((?:(?!\1).)*)\1/);
    if (d) return d[2];
  }
  return null;
}

function checkLength(kind, value, min, max) {
  const findings = [];
  const isPlaceholder = PLACEHOLDERS.some((p) => value.toLowerCase().includes(p));
  if (isPlaceholder) {
    findings.push(`${kind} is boilerplate/placeholder text: "${value}"`);
  }
  if (value.length < min) {
    findings.push(`${kind} is ${value.length} chars — too short (aim for ${min}-${max}): "${value}"`);
  } else if (value.length > max) {
    findings.push(`${kind} is ${value.length} chars — will likely truncate in search results (aim for ${min}-${max}): "${value}"`);
  }
  return findings;
}

function auditFile(path) {
  const text = readFileSync(path, "utf8");
  const findings = [];
  const anchors = [];

  for (const m of text.matchAll(/export\s+const\s+metadata\s*(?::\s*Metadata)?\s*=/g)) {
    anchors.push(m.index + m[0].length);
  }
  for (const m of text.matchAll(/function\s+generateMetadata[\s\S]*?return\s*/g)) {
    anchors.push(m.index + m[0].length);
  }

  for (const anchor of anchors) {
    const obj = extractObjectLiteral(text, anchor);
    if (!obj) continue;
    const title = extractField(obj, "title");
    const description = extractField(obj, "description");
    if (title) findings.push(...checkLength("title", title, TITLE_MIN, TITLE_MAX));
    if (description) findings.push(...checkLength("description", description, DESC_MIN, DESC_MAX));
  }

  return findings;
}

function main() {
  const files = statSync(root).isDirectory() ? walk(root) : [root];
  let total = 0;
  for (const file of files) {
    const findings = auditFile(file);
    if (findings.length) {
      total += findings.length;
      console.log(`\n${relative(process.cwd(), file)}`);
      for (const f of findings) console.log(`  ${f}`);
    }
  }
  console.log(`\nportfolio-writing SEO check: ${total} finding(s) in ${root}`);
  process.exitCode = total > 0 ? 1 : 0;
}

main();
