// Arms -- biceps/triceps isolation work. Currently the thinnest coverage
// in the catalog (biceps: 7 rows, mostly secondary from pulls/rows).
export default [
  {
    slug: "barbell-curl",
    name: "Barbell Curl",
    difficulty: "beginner",
    pattern: "pull",
    primary: ["biceps"],
    secondary: ["forearms"],
    equipment: ["barbell"],
    instructions: "De pie, flexiona los codos elevando la barra hasta la altura del hombro sin mover el torso.",
    mistakes: "Balancear la cadera para generar impulso.",
  },
  {
    slug: "ez-bar-curl",
    name: "EZ-Bar Curl",
    difficulty: "beginner",
    pattern: "pull",
    primary: ["biceps"],
    secondary: ["forearms"],
    equipment: ["barbell"],
    instructions: "Con la barra Z, flexiona los codos elevando el peso manteniendo los codos pegados al torso.",
    mistakes: "Abrir los codos hacia fuera durante la subida.",
  },
  {
    slug: "dumbbell-curl",
    name: "Dumbbell Curl",
    difficulty: "beginner",
    pattern: "pull",
    primary: ["biceps"],
    secondary: ["forearms"],
    equipment: ["dumbbells"],
    instructions: "De pie, flexiona alternando o a la vez los codos elevando las mancuernas hasta el hombro.",
    mistakes: "Rotar el hombro hacia delante para ayudar a subir el peso.",
  },
  {
    slug: "hammer-curl",
    name: "Hammer Curl",
    difficulty: "beginner",
    pattern: "pull",
    primary: ["biceps", "forearms"],
    secondary: [],
    equipment: ["dumbbells"],
    instructions: "Con agarre neutro (palmas encaradas), flexiona los codos elevando las mancuernas sin rotar la muñeca.",
    mistakes: "Usar impulso del hombro en vez de flexión pura de codo.",
  },
  {
    slug: "incline-dumbbell-curl",
    name: "Incline Dumbbell Curl",
    difficulty: "intermediate",
    pattern: "pull",
    primary: ["biceps"],
    secondary: [],
    equipment: ["dumbbells", "bench"],
    instructions: "Sentado en banco inclinado con los brazos colgando, flexiona los codos manteniendo los hombros hacia atrás.",
    mistakes: "Adelantar el hombro perdiendo el estiramiento del bíceps.",
  },
  {
    slug: "preacher-curl",
    name: "Preacher Curl",
    difficulty: "intermediate",
    pattern: "pull",
    primary: ["biceps"],
    secondary: [],
    equipment: ["barbell", "bench"],
    instructions: "Con el brazo apoyado en el banco predicador, flexiona el codo sin despegar el tríceps del apoyo.",
    mistakes: "Extender completamente el codo de golpe al bajar el peso.",
  },
  {
    slug: "concentration-curl",
    name: "Concentration Curl",
    difficulty: "beginner",
    pattern: "pull",
    primary: ["biceps"],
    secondary: [],
    equipment: ["dumbbells"],
    instructions: "Sentado, apoya el codo en la cara interna del muslo y flexiona la mancuerna hacia el hombro.",
    mistakes: "Mover el codo del punto de apoyo durante la repetición.",
  },
  {
    slug: "cable-curl",
    name: "Cable Curl",
    difficulty: "beginner",
    pattern: "pull",
    primary: ["biceps"],
    secondary: ["forearms"],
    equipment: ["cable_machine"],
    instructions: "Con la polea baja, flexiona los codos tirando de la barra hacia el hombro sin mover el torso.",
    mistakes: "Inclinar el torso hacia atrás para ayudar a subir el peso.",
  },
  {
    slug: "reverse-curl",
    name: "Reverse Curl",
    difficulty: "intermediate",
    pattern: "pull",
    primary: ["forearms", "biceps"],
    secondary: [],
    equipment: ["barbell"],
    instructions: "Con agarre prono (palmas hacia abajo), flexiona los codos elevando la barra hasta la altura del hombro.",
    mistakes: "Usar peso excesivo que obliga a compensar con la muñeca.",
  },
  {
    slug: "drag-curl",
    name: "Drag Curl",
    difficulty: "intermediate",
    pattern: "pull",
    primary: ["biceps"],
    secondary: [],
    equipment: ["barbell"],
    instructions: "Mantén la barra pegada al cuerpo mientras flexionas el codo, llevando el codo hacia atrás en vez de adelante.",
    mistakes: "Separar la barra del cuerpo convirtiéndolo en un curl estándar.",
  },
  {
    slug: "triceps-pushdown",
    name: "Triceps Pushdown",
    difficulty: "beginner",
    pattern: "push",
    primary: ["triceps"],
    secondary: [],
    equipment: ["cable_machine"],
    instructions: "Con la polea alta, extiende los codos empujando la barra hacia abajo sin despegar los codos del torso.",
    mistakes: "Separar los codos del cuerpo durante la extensión.",
  },
  {
    slug: "overhead-triceps-extension",
    name: "Overhead Triceps Extension",
    difficulty: "intermediate",
    pattern: "push",
    primary: ["triceps"],
    secondary: [],
    equipment: ["dumbbells"],
    instructions: "Con la mancuerna sujeta por encima de la cabeza, flexiona los codos bajándola detrás de la cabeza y extiende de vuelta.",
    mistakes: "Abrir los codos hacia los lados en vez de mantenerlos apuntando al frente.",
  },
  {
    slug: "skull-crusher",
    name: "Skull Crusher",
    difficulty: "intermediate",
    pattern: "push",
    primary: ["triceps"],
    secondary: [],
    equipment: ["barbell", "bench"],
    instructions: "Tumbado en banco, baja la barra hacia la frente flexionando solo el codo y extiende de vuelta.",
    mistakes: "Mover el hombro durante la flexión en vez de fijarlo.",
  },
  {
    slug: "cable-overhead-extension",
    name: "Cable Overhead Extension",
    difficulty: "intermediate",
    pattern: "push",
    primary: ["triceps"],
    secondary: [],
    equipment: ["cable_machine"],
    instructions: "De espaldas a la polea baja, extiende los codos por encima de la cabeza empujando la cuerda hacia arriba.",
    mistakes: "Arquear la espalda baja para ganar recorrido.",
  },
  {
    slug: "dumbbell-kickback",
    name: "Dumbbell Kickback",
    difficulty: "beginner",
    pattern: "push",
    primary: ["triceps"],
    secondary: [],
    equipment: ["dumbbells", "bench"],
    instructions: "Torso inclinado y brazo paralelo al suelo, extiende el codo llevando la mancuerna hacia atrás.",
    mistakes: "Bajar el brazo por debajo de la línea del torso durante la extensión.",
  },
  {
    slug: "machine-triceps-extension",
    name: "Machine Triceps Extension",
    difficulty: "beginner",
    pattern: "push",
    primary: ["triceps"],
    secondary: [],
    equipment: ["gym_machine"],
    instructions: "Codos apoyados en el cojín, extiende los antebrazos empujando los manillares hacia abajo.",
    mistakes: "Despegar los codos del apoyo durante la extensión.",
  },
  {
    slug: "wrist-curl",
    name: "Wrist Curl",
    difficulty: "beginner",
    pattern: "pull",
    primary: ["forearms"],
    secondary: [],
    equipment: ["dumbbells"],
    instructions: "Antebrazos apoyados en el muslo o banco, flexiona solo la muñeca elevando el peso.",
    mistakes: "Mover el codo en vez de aislar el movimiento en la muñeca.",
  },
];
