// Back -- rows, pulldowns, pullovers, shrugs not already in the catalog.
const exercises = [
  {
    slug: "seated-cable-row",
    name: "Seated Cable Row",
    difficulty: "beginner",
    pattern: "pull",
    primary: ["back", "lats"],
    secondary: ["biceps", "forearms"],
    equipment: ["cable_machine"],
    instructions: "Sentado con rodillas ligeramente flexionadas, tira del agarre hacia el abdomen manteniendo la espalda recta.",
    mistakes: "Balancear el torso hacia atrás para ayudar a tirar del peso.",
  },
  {
    slug: "single-arm-dumbbell-row",
    name: "Single-Arm Dumbbell Row",
    difficulty: "beginner",
    pattern: "pull",
    primary: ["back", "lats"],
    secondary: ["biceps", "forearms"],
    equipment: ["dumbbells", "bench"],
    instructions: "Apoya rodilla y mano en el banco, tira de la mancuerna hacia la cadera manteniendo el torso paralelo al suelo.",
    mistakes: "Rotar el torso para ganar recorrido en vez de tirar solo con el brazo.",
  },
  {
    slug: "chest-supported-row",
    name: "Chest-Supported Row",
    difficulty: "beginner",
    pattern: "pull",
    primary: ["back"],
    secondary: ["biceps"],
    equipment: ["dumbbells", "bench"],
    instructions: "Tumbado boca abajo sobre un banco inclinado, tira de las mancuernas hacia la cadera sin usar impulso.",
    mistakes: "Despegar el pecho del banco para generar impulso.",
  },
  {
    slug: "t-bar-row",
    name: "T-Bar Row",
    difficulty: "intermediate",
    pattern: "pull",
    primary: ["back"],
    secondary: ["biceps", "forearms"],
    equipment: ["barbell"],
    instructions: "Con el torso inclinado y la barra entre las piernas, tira del agarre hacia el pecho contrayendo la espalda.",
    mistakes: "Extender la espalda baja en vez de mantenerla neutra durante la tracción.",
  },
  {
    slug: "machine-row",
    name: "Machine Row",
    difficulty: "beginner",
    pattern: "pull",
    primary: ["back"],
    secondary: ["biceps"],
    equipment: ["gym_machine"],
    instructions: "Pecho apoyado en el respaldo, tira de los manillares hacia atrás contrayendo los omóplatos.",
    mistakes: "Usar solo los brazos sin retraer la escápula.",
  },
  {
    slug: "straight-arm-pulldown",
    name: "Straight-Arm Pulldown",
    difficulty: "intermediate",
    pattern: "pull",
    primary: ["lats"],
    secondary: ["core"],
    equipment: ["cable_machine"],
    instructions: "Con los brazos extendidos, tira de la barra hacia los muslos manteniendo un ligero doblez de codo constante.",
    mistakes: "Flexionar el codo durante el descenso, convirtiéndolo en un press.",
  },
  {
    slug: "dumbbell-pullover",
    name: "Dumbbell Pullover",
    difficulty: "intermediate",
    pattern: "pull",
    primary: ["lats", "chest"],
    secondary: ["core"],
    equipment: ["dumbbells", "bench"],
    instructions: "Tumbado perpendicular al banco, baja la mancuerna en arco por detrás de la cabeza y vuelve a subirla sobre el pecho.",
    mistakes: "Arquear excesivamente la espalda baja durante el descenso.",
  },
  {
    slug: "wide-grip-lat-pulldown",
    name: "Wide-Grip Lat Pulldown",
    difficulty: "beginner",
    pattern: "pull",
    primary: ["lats"],
    secondary: ["biceps"],
    equipment: ["cable_machine"],
    instructions: "Agarre ancho, tira de la barra hacia la parte alta del pecho manteniendo el torso ligeramente inclinado hacia atrás.",
    mistakes: "Tirar de la barra por detrás de la nuca.",
  },
  {
    slug: "close-grip-lat-pulldown",
    name: "Close-Grip Lat Pulldown",
    difficulty: "beginner",
    pattern: "pull",
    primary: ["lats"],
    secondary: ["biceps"],
    equipment: ["cable_machine"],
    instructions: "Agarre estrecho neutro, tira de la barra hacia el pecho contrayendo la espalda al final del recorrido.",
    mistakes: "Recorrido parcial sin extender completamente los brazos al subir.",
  },
  {
    slug: "barbell-shrug",
    name: "Barbell Shrug",
    difficulty: "beginner",
    pattern: "pull",
    primary: ["back"],
    secondary: ["forearms"],
    equipment: ["barbell"],
    instructions: "Sujeta la barra con los brazos extendidos y eleva los hombros directamente hacia arriba sin flexionar el codo.",
    mistakes: "Rotar los hombros en vez de elevarlos en línea recta.",
  },
  {
    slug: "dumbbell-shrug",
    name: "Dumbbell Shrug",
    difficulty: "beginner",
    pattern: "pull",
    primary: ["back"],
    secondary: ["forearms"],
    equipment: ["dumbbells"],
    instructions: "Con una mancuerna en cada mano, eleva los hombros directamente hacia arriba y controla el descenso.",
    mistakes: "Usar impulso de las piernas para ayudar a elevar el peso.",
  },
  {
    slug: "good-morning",
    name: "Good Morning",
    difficulty: "advanced",
    pattern: "hinge",
    primary: ["hamstrings", "back"],
    secondary: ["glutes"],
    equipment: ["barbell"],
    instructions: "Barra sobre los trapecios, inclina el torso hacia delante con bisagra de cadera manteniendo las rodillas casi extendidas.",
    mistakes: "Redondear la espalda baja en vez de mantenerla neutra.",
  },
  {
    slug: "landmine-row",
    name: "Landmine Row",
    difficulty: "intermediate",
    pattern: "pull",
    primary: ["back"],
    secondary: ["biceps"],
    equipment: ["barbell"],
    instructions: "Con un extremo de la barra anclado, tira del otro extremo hacia el torso manteniendo la espalda neutra.",
    mistakes: "Extender la espalda baja para ayudar a tirar del peso.",
  },
  {
    slug: "renegade-row",
    name: "Renegade Row",
    difficulty: "advanced",
    pattern: "pull",
    primary: ["back", "core"],
    secondary: ["shoulders"],
    equipment: ["dumbbells"],
    instructions: "En posición de plancha con las manos sobre mancuernas, tira alternando un brazo hacia la cadera manteniendo la cadera estable.",
    mistakes: "Rotar la cadera hacia el lado que tira en vez de mantenerla cuadrada.",
  },
  {
    slug: "rack-pull",
    name: "Rack Pull",
    difficulty: "intermediate",
    pattern: "hinge",
    primary: ["back", "hamstrings"],
    secondary: ["glutes", "forearms"],
    equipment: ["barbell"],
    instructions: "Desde soportes a la altura de la rodilla, levanta la barra extendiendo cadera y rodillas hasta quedar erguido.",
    mistakes: "Empezar con la espalda redondeada por la altura reducida del recorrido.",
  },
  {
    slug: "sumo-deadlift",
    name: "Sumo Deadlift",
    difficulty: "intermediate",
    pattern: "hinge",
    primary: ["glutes", "hamstrings"],
    secondary: ["back", "quadriceps"],
    equipment: ["barbell"],
    instructions: "Pies muy separados y puntas hacia fuera, levanta la barra manteniéndola pegada al cuerpo con el torso más vertical.",
    mistakes: "Rodillas colapsando hacia dentro durante el tirón.",
  },
];

export default exercises;
