// Resistance bands -- banded-hip-abduction and monster-walk already live
// in legs.mjs (they're leg-focused despite the equipment). face-pull
// already exists in the catalog (unlinked to any equipment there).
export default [
  {
    slug: "band-row",
    name: "Band Row",
    difficulty: "beginner",
    pattern: "pull",
    primary: ["back"],
    secondary: ["biceps"],
    equipment: ["resistance_band"],
    instructions: "Con la banda anclada al frente, tira de los extremos hacia la cadera contrayendo la espalda.",
    mistakes: "Encoger los hombros en vez de retraer las escápulas.",
  },
  {
    slug: "band-chest-press",
    name: "Band Chest Press",
    difficulty: "beginner",
    pattern: "push",
    primary: ["chest"],
    secondary: ["triceps"],
    equipment: ["resistance_band"],
    instructions: "Con la banda anclada detrás, empuja los extremos al frente hasta extensión completa de brazos.",
    mistakes: "Arquear la espalda para ganar recorrido.",
  },
  {
    slug: "band-curl",
    name: "Band Curl",
    difficulty: "beginner",
    pattern: "pull",
    primary: ["biceps"],
    secondary: ["forearms"],
    equipment: ["resistance_band"],
    instructions: "De pie sobre la banda, flexiona los codos elevando los extremos hasta el hombro.",
    mistakes: "Balancear el torso para ayudar a subir la banda.",
  },
  {
    slug: "band-triceps-pushdown",
    name: "Band Triceps Pushdown",
    difficulty: "beginner",
    pattern: "push",
    primary: ["triceps"],
    secondary: [],
    equipment: ["resistance_band"],
    instructions: "Con la banda anclada arriba, extiende los codos empujando hacia abajo sin despegarlos del torso.",
    mistakes: "Separar los codos del cuerpo durante la extensión.",
  },
  {
    slug: "band-lateral-raise",
    name: "Band Lateral Raise",
    difficulty: "beginner",
    pattern: "push",
    primary: ["shoulders"],
    secondary: [],
    equipment: ["resistance_band"],
    instructions: "De pie sobre la banda, eleva el brazo lateralmente hasta la altura del hombro con codo ligeramente flexionado.",
    mistakes: "Encoger el hombro durante la elevación.",
  },
  {
    slug: "band-pull-apart",
    name: "Band Pull-Apart",
    difficulty: "beginner",
    pattern: "pull",
    primary: ["shoulders", "back"],
    secondary: [],
    equipment: ["resistance_band"],
    instructions: "Con los brazos extendidos al frente, separa la banda llevando los brazos hacia los lados contrayendo la espalda alta.",
    mistakes: "Flexionar los codos en vez de mantener los brazos extendidos.",
  },
  {
    slug: "band-face-pull",
    name: "Band Face Pull",
    difficulty: "beginner",
    pattern: "pull",
    primary: ["shoulders"],
    secondary: ["back"],
    equipment: ["resistance_band"],
    instructions: "Con la banda anclada a la altura de la cara, tira de los extremos hacia la cara separando los codos.",
    mistakes: "Tirar hacia el pecho en vez de hacia la cara.",
  },
  {
    slug: "band-squat",
    name: "Band Squat",
    difficulty: "beginner",
    pattern: "squat",
    primary: ["quadriceps", "glutes"],
    secondary: ["hamstrings"],
    equipment: ["resistance_band"],
    instructions: "Con la banda sobre los hombros y anclada bajo los pies, desciende hasta muslos paralelos al suelo y sube.",
    mistakes: "Perder la tensión de la banda al no descender lo suficiente.",
  },
  {
    slug: "band-good-morning",
    name: "Band Good Morning",
    difficulty: "intermediate",
    pattern: "hinge",
    primary: ["hamstrings", "back"],
    secondary: ["glutes"],
    equipment: ["resistance_band"],
    instructions: "Con la banda sobre los hombros y bajo los pies, inclina el torso al frente con bisagra de cadera y vuelve a subir.",
    mistakes: "Redondear la espalda baja en vez de mantenerla neutra.",
  },
  {
    slug: "band-deadlift",
    name: "Band Deadlift",
    difficulty: "beginner",
    pattern: "hinge",
    primary: ["hamstrings", "glutes"],
    secondary: ["back"],
    equipment: ["resistance_band"],
    instructions: "De pie sobre la banda, realiza una bisagra de cadera y extiende hasta quedar completamente erguido.",
    mistakes: "Redondear la espalda baja durante el ascenso.",
  },
  {
    slug: "band-overhead-press",
    name: "Band Overhead Press",
    difficulty: "beginner",
    pattern: "push",
    primary: ["shoulders"],
    secondary: ["triceps"],
    equipment: ["resistance_band"],
    instructions: "De pie sobre la banda, empuja los extremos por encima de la cabeza hasta extensión completa.",
    mistakes: "Arquear la espalda baja para ayudar a completar el empuje.",
  },
  {
    slug: "band-glute-kickback",
    name: "Band Glute Kickback",
    difficulty: "beginner",
    pattern: "hinge",
    primary: ["glutes"],
    secondary: ["hamstrings"],
    equipment: ["resistance_band"],
    instructions: "En cuadrupedia con la banda alrededor de un pie, extiende la cadera llevando la pierna hacia atrás y arriba.",
    mistakes: "Arquear la espalda baja para ganar recorrido.",
  },
];
