// Cable machine -- movements not already placed by muscle group elsewhere
// (chest.mjs has both cable flys; back.mjs has seated-cable-row,
// straight-arm-pulldown, wide/close-grip lat pulldown; shoulders.mjs has
// cable-lateral/front-raise; arms.mjs has cable-curl, triceps-pushdown,
// cable-overhead-extension; legs.mjs has cable-pull-through,
// cable-glute-kickback; core.mjs has cable-crunch, pallof-press,
// woodchopper. face-pull already exists in the base catalog.
export default [
  {
    slug: "cable-upright-row",
    name: "Cable Upright Row",
    difficulty: "intermediate",
    pattern: "pull",
    primary: ["shoulders"],
    secondary: ["back", "forearms"],
    equipment: ["cable_machine"],
    instructions: "Con la polea baja, tira de la barra verticalmente pegada al cuerpo hasta la altura del pecho.",
    mistakes: "Elevar el peso por encima de la altura del hombro.",
  },
  {
    slug: "single-arm-cable-row",
    name: "Single-Arm Cable Row",
    difficulty: "beginner",
    pattern: "pull",
    primary: ["back"],
    secondary: ["biceps"],
    equipment: ["cable_machine"],
    instructions: "Sentado con un solo agarre, tira hacia la cadera manteniendo el torso estable sin rotar.",
    mistakes: "Rotar el torso para ayudar a completar la tracción.",
  },
  {
    slug: "cable-kickback",
    name: "Cable Kickback",
    difficulty: "beginner",
    pattern: "push",
    primary: ["triceps"],
    secondary: [],
    equipment: ["cable_machine"],
    instructions: "Torso inclinado con la polea baja, extiende el codo llevando el agarre hacia atrás.",
    mistakes: "Bajar el brazo por debajo de la línea del torso durante la extensión.",
  },
  {
    slug: "cable-face-pull",
    name: "Cable Face Pull",
    difficulty: "beginner",
    pattern: "pull",
    primary: ["shoulders"],
    secondary: ["back"],
    equipment: ["cable_machine"],
    instructions: "Con la polea a la altura de la cara, tira de la cuerda hacia la cara separando los codos hacia fuera.",
    mistakes: "Tirar hacia el pecho en vez de hacia la altura de la cara.",
  },
  {
    slug: "standing-cable-chest-press",
    name: "Standing Cable Chest Press",
    difficulty: "beginner",
    pattern: "push",
    primary: ["chest"],
    secondary: ["triceps", "shoulders"],
    equipment: ["cable_machine"],
    instructions: "De pie de espaldas a la polea, empuja los agarres al frente hasta extensión completa de brazos.",
    mistakes: "Inclinar el torso hacia delante en vez de mantenerlo estable.",
  },
  {
    slug: "cable-hip-abduction",
    name: "Cable Hip Abduction",
    difficulty: "beginner",
    pattern: "squat",
    primary: ["glutes"],
    secondary: [],
    equipment: ["cable_machine"],
    instructions: "Con el tobillo enganchado al cable, separa la pierna lateralmente manteniendo el torso estable.",
    mistakes: "Inclinar el torso hacia el lado contrario para ganar recorrido.",
  },
  {
    slug: "cable-shrug",
    name: "Cable Shrug",
    difficulty: "beginner",
    pattern: "pull",
    primary: ["back"],
    secondary: ["forearms"],
    equipment: ["cable_machine"],
    instructions: "De pie frente a la polea baja, eleva los hombros directamente hacia arriba sin flexionar el codo.",
    mistakes: "Rotar los hombros en vez de elevarlos en línea recta.",
  },
];
