// Calisthenics -- recognizable progressions only, nothing fabricated.
// pull-up, chin-up, weighted/assisted/australian pull-up, muscle-up,
// toes-to-bar, dead-hang, l-sit, hollow-body-hold, dip variants,
// handstand-push-up, pike-push-up, diamond/wide/incline push-up already exist.
const exercises = [
  {
    slug: "wide-grip-pull-up",
    name: "Wide-Grip Pull Up",
    difficulty: "intermediate",
    pattern: "pull",
    primary: ["lats", "back"],
    secondary: ["biceps"],
    equipment: ["pull_up_bar"],
    instructions: "Con agarre más ancho que los hombros, tira hasta que la barbilla supere la barra y baja con control.",
    mistakes: "Recorrido parcial por la mayor dificultad del agarre ancho.",
  },
  {
    slug: "neutral-grip-pull-up",
    name: "Neutral-Grip Pull Up",
    difficulty: "intermediate",
    pattern: "pull",
    primary: ["lats", "back"],
    secondary: ["biceps"],
    equipment: ["pull_up_bar"],
    instructions: "Con agarre neutro (palmas encaradas), tira hasta que la barbilla supere las manos y baja con control.",
    mistakes: "Balanceo del cuerpo para ganar impulso.",
  },
  {
    slug: "commando-pull-up",
    name: "Commando Pull Up",
    difficulty: "advanced",
    pattern: "pull",
    primary: ["lats", "back"],
    secondary: ["biceps", "core"],
    equipment: ["pull_up_bar"],
    instructions: "Agarre con las manos una delante de otra, tira alternando el lado de la cabeza que pasa junto a la barra.",
    mistakes: "Rotar excesivamente el torso en vez de tirar en línea recta.",
  },
  {
    slug: "archer-pull-up",
    name: "Archer Pull Up",
    difficulty: "advanced",
    pattern: "pull",
    primary: ["lats", "back"],
    secondary: ["biceps"],
    equipment: ["pull_up_bar"],
    instructions: "Agarre ancho, tira desplazando el peso hacia un lado mientras el otro brazo queda casi extendido.",
    mistakes: "No alcanzar suficiente altura para cargar realmente el lado activo.",
  },
  {
    slug: "typewriter-pull-up",
    name: "Typewriter Pull Up",
    difficulty: "advanced",
    pattern: "pull",
    primary: ["lats", "back"],
    secondary: ["biceps", "core"],
    equipment: ["pull_up_bar"],
    instructions: "Mantén la barbilla sobre la barra y desplaza el cuerpo lateralmente de un lado a otro sin bajar.",
    mistakes: "Perder la altura de la barbilla sobre la barra durante el desplazamiento.",
  },
  {
    slug: "one-arm-pull-up-progression",
    name: "One-Arm Pull Up Progression",
    difficulty: "advanced",
    pattern: "pull",
    primary: ["lats", "back"],
    secondary: ["biceps", "core"],
    equipment: ["pull_up_bar"],
    instructions: "Sujeta la muñeca del brazo activo con la mano libre para asistir parcialmente y tira con un solo brazo dominante.",
    mistakes: "Depender totalmente del brazo asistente en vez de cargar el brazo activo.",
  },
  {
    slug: "l-sit-pull-up",
    name: "L-Sit Pull Up",
    difficulty: "advanced",
    pattern: "pull",
    primary: ["lats", "core"],
    secondary: ["back", "biceps"],
    equipment: ["pull_up_bar"],
    instructions: "Manteniendo las piernas extendidas al frente en L, tira hasta que la barbilla supere la barra.",
    mistakes: "Dejar caer las piernas durante la tracción.",
  },
  {
    slug: "ring-dip",
    name: "Ring Dip",
    difficulty: "advanced",
    pattern: "push",
    primary: ["chest", "triceps"],
    secondary: ["shoulders"],
    equipment: ["suspension_trainer"],
    instructions: "Sujeto en anillas, desciende controlando la estabilidad hasta 90° de codo y empuja de vuelta arriba.",
    mistakes: "Perder la estabilidad de las anillas por falta de control escapular.",
  },
  {
    slug: "weighted-dip",
    name: "Weighted Dip",
    difficulty: "advanced",
    pattern: "push",
    primary: ["chest", "triceps"],
    secondary: ["shoulders"],
    equipment: ["parallel_bars"],
    instructions: "Igual que el fondo estándar, con peso adicional mediante cinturón de lastre o mancuerna sujeta entre los pies.",
    mistakes: "Añadir peso antes de dominar el fondo estricto con buena técnica.",
  },
  {
    slug: "spiderman-push-up",
    name: "Spiderman Push Up",
    difficulty: "intermediate",
    pattern: "push",
    primary: ["chest", "core"],
    secondary: ["triceps"],
    equipment: [],
    instructions: "Durante la flexión, lleva una rodilla hacia el codo del mismo lado y alterna en cada repetición.",
    mistakes: "Rotar la cadera en vez de mantenerla cuadrada al suelo.",
  },
  {
    slug: "one-arm-push-up",
    name: "One-Arm Push Up",
    difficulty: "advanced",
    pattern: "push",
    primary: ["chest", "triceps"],
    secondary: ["core"],
    equipment: [],
    instructions: "Con los pies muy separados para estabilidad, realiza la flexión completa apoyando un solo brazo.",
    mistakes: "Rotar el torso hacia el lado que empuja en vez de mantenerlo cuadrado.",
  },
  {
    slug: "pistol-squat",
    name: "Pistol Squat",
    difficulty: "advanced",
    pattern: "squat",
    primary: ["quadriceps", "glutes"],
    secondary: ["core"],
    equipment: [],
    instructions: "Sobre una pierna, desciende manteniendo la otra pierna extendida al frente hasta profundidad completa y sube.",
    mistakes: "Perder el equilibrio hacia atrás al descender.",
  },
  {
    slug: "shrimp-squat",
    name: "Shrimp Squat",
    difficulty: "advanced",
    pattern: "squat",
    primary: ["quadriceps", "glutes"],
    secondary: ["core"],
    equipment: [],
    instructions: "Sobre una pierna, sujeta el tobillo contrario detrás del cuerpo y desciende hasta que la rodilla trasera casi toque el suelo.",
    mistakes: "Soltar el tobillo sujeto para facilitar el equilibrio.",
  },
  {
    slug: "cossack-squat",
    name: "Cossack Squat",
    difficulty: "intermediate",
    pattern: "squat",
    primary: ["quadriceps", "glutes"],
    secondary: ["hamstrings"],
    equipment: [],
    instructions: "Pies muy separados, desplaza el peso hacia un lado flexionando esa rodilla mientras la otra pierna queda extendida.",
    mistakes: "Despegar el talón de la pierna flexionada del suelo.",
  },
  {
    slug: "front-lever-tuck",
    name: "Front Lever Tuck",
    difficulty: "intermediate",
    pattern: "core",
    primary: ["lats", "core"],
    secondary: ["back"],
    equipment: ["pull_up_bar"],
    instructions: "Colgado de la barra, lleva las rodillas al pecho y horizontaliza el cuerpo manteniendo los brazos extendidos.",
    mistakes: "Flexionar los codos para compensar la falta de fuerza en el dorsal.",
  },
  {
    slug: "front-lever",
    name: "Front Lever",
    difficulty: "advanced",
    pattern: "core",
    primary: ["lats", "core"],
    secondary: ["back"],
    equipment: ["pull_up_bar"],
    instructions: "Colgado de la barra, mantén el cuerpo completamente horizontal y extendido con los brazos rectos.",
    mistakes: "Dejar caer la cadera por debajo de la línea del cuerpo.",
  },
  {
    slug: "back-lever-tuck",
    name: "Back Lever Tuck",
    difficulty: "advanced",
    pattern: "core",
    primary: ["lats", "core"],
    secondary: ["shoulders"],
    equipment: ["pull_up_bar"],
    instructions: "Desde un agarre en pronación por detrás, invierte el cuerpo y mantén las rodillas encogidas horizontales bajo la barra.",
    mistakes: "Abrir los hombros en vez de mantener una rotación controlada.",
  },
  {
    slug: "tuck-planche",
    name: "Tuck Planche",
    difficulty: "advanced",
    pattern: "core",
    primary: ["shoulders", "core"],
    secondary: ["chest"],
    equipment: [],
    instructions: "Con las manos en el suelo y las rodillas encogidas al pecho, inclina los hombros al frente hasta despegar los pies.",
    mistakes: "No inclinar suficiente los hombros al frente, dejando peso en las manos sin despegar.",
  },
  {
    slug: "handstand-hold",
    name: "Handstand Hold",
    difficulty: "intermediate",
    pattern: "core",
    primary: ["shoulders", "core"],
    secondary: ["forearms"],
    equipment: [],
    instructions: "Con apoyo en la pared si es necesario, mantén el cuerpo invertido en línea recta con los brazos extendidos.",
    mistakes: "Arquear la espalda baja en vez de mantener el core activado.",
  },
  {
    slug: "human-flag",
    name: "Human Flag",
    difficulty: "advanced",
    pattern: "core",
    primary: ["lats", "core"],
    secondary: ["shoulders"],
    equipment: ["pull_up_bar"],
    instructions: "Sujeto a un poste vertical con ambas manos, eleva el cuerpo horizontal lateral manteniéndolo recto.",
    mistakes: "Flexionar la cadera perdiendo la línea recta del cuerpo.",
  },
];

export default exercises;
