// Chest -- bench/press/fly variants not already in the catalog.
// Fields match public.exercises + exercise_equipment exactly (see
// supabase/seed/README.md for the full contract and how to add more).
const exercises = [
  {
    slug: "decline-barbell-bench-press",
    name: "Decline Barbell Bench Press",
    difficulty: "intermediate",
    pattern: "push",
    primary: ["chest"],
    secondary: ["triceps"],
    equipment: ["barbell", "bench"],
    instructions: "En banco declinado, baja la barra hasta la parte baja del pecho y empuja a extensión completa.",
    mistakes: "Recorrido demasiado corto por miedo a golpear el pecho.",
  },
  {
    slug: "decline-dumbbell-press",
    name: "Decline Dumbbell Press",
    difficulty: "intermediate",
    pattern: "push",
    primary: ["chest"],
    secondary: ["triceps"],
    equipment: ["dumbbells", "bench"],
    instructions: "En banco declinado, empuja ambas mancuernas desde el pecho hasta la extensión completa de brazos.",
    mistakes: "Chocar las mancuernas antes de completar el bloqueo de codo.",
  },
  {
    slug: "incline-dumbbell-press",
    name: "Incline Dumbbell Press",
    difficulty: "intermediate",
    pattern: "push",
    primary: ["chest"],
    secondary: ["shoulders", "triceps"],
    equipment: ["dumbbells", "bench"],
    instructions: "En banco inclinado a 30-45°, empuja las mancuernas desde la altura del pecho superior hasta arriba.",
    mistakes: "Inclinación excesiva del banco, convirtiéndolo en press de hombro.",
  },
  {
    slug: "close-grip-bench-press",
    name: "Close Grip Bench Press",
    difficulty: "intermediate",
    pattern: "push",
    primary: ["triceps"],
    secondary: ["chest"],
    equipment: ["barbell", "bench"],
    instructions: "Agarre a la anchura de hombros, baja la barra al pecho manteniendo los codos cerca del cuerpo y empuja.",
    mistakes: "Agarre demasiado estrecho que sobrecarga la muñeca.",
  },
  {
    slug: "svend-press",
    name: "Svend Press",
    difficulty: "beginner",
    pattern: "push",
    primary: ["chest"],
    secondary: ["shoulders"],
    equipment: ["plate"],
    instructions: "Presiona dos discos entre las palmas a la altura del pecho y empuja al frente sin separarlos.",
    mistakes: "Perder la presión entre los discos durante el movimiento.",
  },
  {
    slug: "floor-press",
    name: "Floor Press",
    difficulty: "intermediate",
    pattern: "push",
    primary: ["chest"],
    secondary: ["triceps"],
    equipment: ["barbell"],
    instructions: "Tumbado en el suelo, baja la barra hasta que los tríceps toquen el suelo y empuja a extensión completa.",
    mistakes: "Rebotar los codos contra el suelo en vez de controlar el descenso.",
  },
  {
    slug: "dumbbell-fly",
    name: "Dumbbell Fly",
    difficulty: "beginner",
    pattern: "push",
    primary: ["chest"],
    secondary: ["shoulders"],
    equipment: ["dumbbells", "bench"],
    instructions: "Tumbado en banco plano, abre los brazos con codos ligeramente flexionados y junta las mancuernas sobre el pecho.",
    mistakes: "Flexionar completamente el codo convirtiéndolo en un press.",
  },
  {
    slug: "incline-dumbbell-fly",
    name: "Incline Dumbbell Fly",
    difficulty: "intermediate",
    pattern: "push",
    primary: ["chest"],
    secondary: ["shoulders"],
    equipment: ["dumbbells", "bench"],
    instructions: "En banco inclinado, abre los brazos y junta las mancuernas por encima del pecho superior con codos semiflexionados.",
    mistakes: "Bajar demasiado provocando tensión excesiva en el hombro.",
  },
  {
    slug: "cable-fly-low-to-high",
    name: "Cable Fly (Low to High)",
    difficulty: "intermediate",
    pattern: "push",
    primary: ["chest"],
    secondary: ["shoulders"],
    equipment: ["cable_machine"],
    instructions: "Poleas bajas, tira ambos cables en diagonal hacia arriba juntando las manos frente al pecho superior.",
    mistakes: "Usar solo los brazos sin cerrar el pecho al final del recorrido.",
  },
  {
    slug: "cable-fly-high-to-low",
    name: "Cable Fly (High to Low)",
    difficulty: "intermediate",
    pattern: "push",
    primary: ["chest"],
    secondary: ["shoulders"],
    equipment: ["cable_machine"],
    instructions: "Poleas altas, tira ambos cables en diagonal hacia abajo juntando las manos frente a la cadera.",
    mistakes: "Curvar la espalda para ganar recorrido en vez de controlar con el pecho.",
  },
  {
    slug: "chest-press-machine",
    name: "Chest Press Machine",
    difficulty: "beginner",
    pattern: "push",
    primary: ["chest"],
    secondary: ["triceps", "shoulders"],
    equipment: ["gym_machine"],
    instructions: "Ajusta el asiento a la altura del pecho y empuja los manillares hasta extensión sin bloquear violentamente el codo.",
    mistakes: "Asiento demasiado bajo o alto, cambiando el ángulo de empuje.",
  },
  {
    slug: "pec-deck",
    name: "Pec Deck",
    difficulty: "beginner",
    pattern: "push",
    primary: ["chest"],
    secondary: [],
    equipment: ["gym_machine"],
    instructions: "Antebrazos apoyados en los cojines, junta los brazos al frente contrayendo el pecho.",
    mistakes: "Impulsar con los hombros en vez de cerrar con el pecho.",
  },
  {
    slug: "decline-push-up",
    name: "Decline Push Up",
    difficulty: "intermediate",
    pattern: "push",
    primary: ["chest", "shoulders"],
    secondary: ["triceps", "core"],
    equipment: ["bench"],
    instructions: "Pies elevados sobre un banco, realiza la flexión manteniendo el cuerpo en línea recta.",
    mistakes: "Cadera caída por falta de tensión en el core.",
  },
  {
    slug: "archer-push-up",
    name: "Archer Push Up",
    difficulty: "advanced",
    pattern: "push",
    primary: ["chest", "triceps"],
    secondary: ["shoulders", "core"],
    equipment: [],
    instructions: "Manos muy separadas, desplaza el peso hacia un lado flexionando ese codo mientras el otro brazo queda extendido.",
    mistakes: "Rotar la cadera en vez de mantenerla cuadrada al suelo.",
  },
  {
    slug: "hindu-push-up",
    name: "Hindu Push Up",
    difficulty: "intermediate",
    pattern: "push",
    primary: ["chest", "shoulders"],
    secondary: ["core"],
    equipment: [],
    instructions: "Desde posición de V invertida, desciende la cadera en arco pasando cerca del suelo hasta terminar con el pecho elevado.",
    mistakes: "Cortar el recorrido en arco en vez de deslizar todo el cuerpo.",
  },
];

export default exercises;
