// Core -- plank/, crunches/rotational not already in the catalog.
// plank, side-plank, crunch, russian-twist, v-up, hanging-leg-raise,
// hanging-knee-raise, arch-hold, l-sit, hollow-body-hold already exist.
export default [
  {
    slug: "dead-bug",
    name: "Dead Bug",
    difficulty: "beginner",
    pattern: "core",
    primary: ["core"],
    secondary: [],
    equipment: ["mat"],
    instructions: "Tumbado boca arriba con brazos y piernas elevados, extiende brazo y pierna opuestos sin despegar la espalda baja del suelo.",
    mistakes: "Arquear la espalda baja al extender la pierna.",
  },
  {
    slug: "bird-dog",
    name: "Bird Dog",
    difficulty: "beginner",
    pattern: "core",
    primary: ["core"],
    secondary: ["glutes", "back"],
    equipment: ["mat"],
    instructions: "En cuadrupedia, extiende brazo y pierna opuestos manteniendo la cadera y los hombros nivelados.",
    mistakes: "Rotar la cadera al extender la pierna.",
  },
  {
    slug: "ab-wheel-rollout",
    name: "Ab Wheel Rollout",
    difficulty: "advanced",
    pattern: "core",
    primary: ["core"],
    secondary: ["shoulders", "lats"],
    equipment: ["ab_wheel"],
    instructions: "De rodillas, rueda la rueda hacia delante extendiendo el cuerpo y regresa contrayendo el abdomen sin arquear la espalda.",
    mistakes: "Dejar caer la cadera perdiendo la línea recta del cuerpo.",
  },
  {
    slug: "cable-crunch",
    name: "Cable Crunch",
    difficulty: "beginner",
    pattern: "core",
    primary: ["core"],
    secondary: [],
    equipment: ["cable_machine"],
    instructions: "De rodillas frente a la polea alta, flexiona el torso llevando los codos hacia las rodillas contrayendo el abdomen.",
    mistakes: "Mover solo los brazos en vez de flexionar la columna.",
  },
  {
    slug: "reverse-crunch",
    name: "Reverse Crunch",
    difficulty: "beginner",
    pattern: "core",
    primary: ["core"],
    secondary: [],
    equipment: ["mat"],
    instructions: "Tumbado boca arriba, eleva la cadera del suelo llevando las rodillas hacia el pecho.",
    mistakes: "Usar impulso de las piernas en vez de contraer el abdomen inferior.",
  },
  {
    slug: "bicycle-crunch",
    name: "Bicycle Crunch",
    difficulty: "beginner",
    pattern: "rotation",
    primary: ["core"],
    secondary: [],
    equipment: ["mat"],
    instructions: "Tumbado boca arriba, lleva el codo hacia la rodilla contraria alternando en un movimiento de pedaleo.",
    mistakes: "Tirar del cuello con las manos en vez de rotar el torso.",
  },
  {
    slug: "mountain-climber",
    name: "Mountain Climber",
    difficulty: "beginner",
    pattern: "core",
    primary: ["core"],
    secondary: ["shoulders", "quadriceps"],
    equipment: [],
    instructions: "En posición de plancha alta, lleva las rodillas alternando hacia el pecho manteniendo la cadera estable.",
    mistakes: "Elevar la cadera perdiendo la línea recta del cuerpo.",
  },
  {
    slug: "pallof-press",
    name: "Pallof Press",
    difficulty: "intermediate",
    pattern: "rotation",
    primary: ["core"],
    secondary: [],
    equipment: ["cable_machine"],
    instructions: "De pie lateral a la polea, empuja el agarre al frente resistiendo la rotación del torso hacia el cable.",
    mistakes: "Dejar que el torso rote hacia la polea durante el empuje.",
  },
  {
    slug: "band-pallof-press",
    name: "Band Pallof Press",
    difficulty: "beginner",
    pattern: "rotation",
    primary: ["core"],
    secondary: [],
    equipment: ["resistance_band"],
    instructions: "De pie lateral al anclaje de la banda, empuja el agarre al frente resistiendo la rotación del torso.",
    mistakes: "Dar un paso demasiado corto que reduce la tensión de la banda.",
  },
  {
    slug: "woodchopper",
    name: "Cable Woodchopper",
    difficulty: "intermediate",
    pattern: "rotation",
    primary: ["core"],
    secondary: ["shoulders"],
    equipment: ["cable_machine"],
    instructions: "Con la polea alta, tira del agarre en diagonal cruzando el cuerpo hasta la cadera contraria rotando el torso.",
    mistakes: "Mover solo los brazos en vez de rotar desde el torso.",
  },
  {
    slug: "dragon-flag",
    name: "Dragon Flag",
    difficulty: "advanced",
    pattern: "core",
    primary: ["core"],
    secondary: ["back"],
    equipment: ["bench"],
    instructions: "Sujeto por detrás de la cabeza, eleva el cuerpo recto desde los hombros y baja con control sin tocar el banco.",
    mistakes: "Flexionar la cadera perdiendo la línea recta del cuerpo.",
  },
  {
    slug: "knee-tuck",
    name: "Knee Tuck",
    difficulty: "beginner",
    pattern: "core",
    primary: ["core"],
    secondary: [],
    equipment: ["bench"],
    instructions: "Sentado con manos apoyadas a los lados, lleva las rodillas hacia el pecho y extiende de vuelta.",
    mistakes: "Balancear el torso en vez de aislar el movimiento en el abdomen.",
  },
];
