// Kettlebell -- kettlebell-swing, kettlebell-snatch, turkish-get-up,
// goblet-squat, farmers-carry already exist.
const exercises = [
  {
    slug: "kettlebell-clean",
    name: "Kettlebell Clean",
    difficulty: "intermediate",
    pattern: "hinge",
    primary: ["hamstrings", "glutes"],
    secondary: ["shoulders", "forearms"],
    equipment: ["kettlebell"],
    instructions: "Con bisagra de cadera, lleva la kettlebell del suelo al hombro en un único movimiento fluido, recibiéndola en el antebrazo.",
    mistakes: "Golpear el antebrazo con la kettlebell por una trayectoria demasiado alejada del cuerpo.",
  },
  {
    slug: "kettlebell-press",
    name: "Kettlebell Press",
    difficulty: "intermediate",
    pattern: "push",
    primary: ["shoulders"],
    secondary: ["triceps", "core"],
    equipment: ["kettlebell"],
    instructions: "Desde la posición de rack, empuja la kettlebell por encima de la cabeza hasta extensión completa del brazo.",
    mistakes: "Arquear la espalda baja para ayudar a completar el bloqueo.",
  },
  {
    slug: "single-arm-kettlebell-press",
    name: "Single-Arm Kettlebell Press",
    difficulty: "intermediate",
    pattern: "push",
    primary: ["shoulders"],
    secondary: ["core"],
    equipment: ["kettlebell"],
    instructions: "Desde el rack con un solo brazo, empuja la kettlebell arriba manteniendo el torso estable sin inclinarse lateralmente.",
    mistakes: "Inclinar el torso hacia el lado contrario para compensar el peso.",
  },
  {
    slug: "kettlebell-row",
    name: "Kettlebell Row",
    difficulty: "beginner",
    pattern: "pull",
    primary: ["back"],
    secondary: ["biceps", "forearms"],
    equipment: ["kettlebell"],
    instructions: "Torso inclinado, tira de la kettlebell hacia la cadera manteniendo la espalda neutra.",
    mistakes: "Rotar el torso para ayudar a completar la tracción.",
  },
  {
    slug: "kettlebell-goblet-lunge",
    name: "Kettlebell Goblet Lunge",
    difficulty: "intermediate",
    pattern: "locomotion",
    primary: ["quadriceps", "glutes"],
    secondary: ["core"],
    equipment: ["kettlebell"],
    instructions: "Sujetando la kettlebell contra el pecho, da un paso adelante y desciende hasta que ambas rodillas formen 90°.",
    mistakes: "Inclinar el torso hacia delante perdiendo la postura vertical.",
  },
  {
    slug: "kettlebell-halo",
    name: "Kettlebell Halo",
    difficulty: "beginner",
    pattern: "rotation",
    primary: ["shoulders"],
    secondary: ["core"],
    equipment: ["kettlebell"],
    instructions: "Sujeta la kettlebell por el asa invertida y rota alrededor de la cabeza manteniendo el torso estable.",
    mistakes: "Mover el torso en vez de aislar el movimiento en los hombros.",
  },
  {
    slug: "kettlebell-windmill",
    name: "Kettlebell Windmill",
    difficulty: "advanced",
    pattern: "rotation",
    primary: ["core", "shoulders"],
    secondary: ["hamstrings"],
    equipment: ["kettlebell"],
    instructions: "Con la kettlebell bloqueada por encima de la cabeza, inclina el torso hacia el lado contrario manteniendo la vista en el peso.",
    mistakes: "Flexionar la rodilla de la pierna que soporta el peso en vez de mantenerla extendida.",
  },
  {
    slug: "double-kettlebell-front-squat",
    name: "Double Kettlebell Front Squat",
    difficulty: "intermediate",
    pattern: "squat",
    primary: ["quadriceps", "glutes"],
    secondary: ["core"],
    equipment: ["kettlebell"],
    instructions: "Con una kettlebell en cada hombro en posición de rack, desciende manteniendo el torso vertical.",
    mistakes: "Dejar caer los codos, perdiendo la posición de rack.",
  },
  {
    slug: "kettlebell-figure-8",
    name: "Kettlebell Figure 8",
    difficulty: "beginner",
    pattern: "rotation",
    primary: ["core"],
    secondary: ["forearms"],
    equipment: ["kettlebell"],
    instructions: "Con las piernas separadas, pasa la kettlebell entre las piernas de una mano a otra dibujando un ocho.",
    mistakes: "Perder el ritmo del movimiento por sujetar el peso demasiado lejos del cuerpo.",
  },
  {
    slug: "kettlebell-around-the-world",
    name: "Kettlebell Around the World",
    difficulty: "beginner",
    pattern: "rotation",
    primary: ["core"],
    secondary: ["forearms"],
    equipment: ["kettlebell"],
    instructions: "Rota la kettlebell alrededor de la cintura pasándola de una mano a otra manteniendo el torso estable.",
    mistakes: "Inclinar el torso para compensar el peso en vez de mantenerlo erguido.",
  },
];

export default exercises;
