// Legs -- quads/hamstrings/glutes/calves not already in the catalog.
// front-squat, barbell-squat, goblet-squat, romanian-deadlift,
// conventional-deadlift, bulgarian-split-squat, hip-thrust, glute-bridge,
// leg-press/-extension/-curl, calf-raise, zercher-squat, step-up,
// reverse-lunge, walking-lunge already exist -- not repeated here.
const exercises = [
  {
    slug: "hack-squat",
    name: "Hack Squat",
    difficulty: "intermediate",
    pattern: "squat",
    primary: ["quadriceps"],
    secondary: ["glutes"],
    equipment: ["gym_machine"],
    instructions: "Espalda apoyada en el respaldo inclinado, desciende flexionando rodillas hasta 90° y empuja de vuelta.",
    mistakes: "Despegar la zona lumbar del respaldo durante el descenso.",
  },
  {
    slug: "sissy-squat",
    name: "Sissy Squat",
    difficulty: "advanced",
    pattern: "squat",
    primary: ["quadriceps"],
    secondary: ["core"],
    equipment: [],
    instructions: "Sujeto de un punto fijo, inclina el torso hacia atrás flexionando solo la rodilla mientras el cuerpo baja en línea recta.",
    mistakes: "Flexionar la cadera en vez de aislar el movimiento en la rodilla.",
  },
  {
    slug: "sumo-squat",
    name: "Sumo Squat",
    difficulty: "beginner",
    pattern: "squat",
    primary: ["glutes", "quadriceps"],
    secondary: ["hamstrings"],
    equipment: ["dumbbells"],
    instructions: "Pies muy separados y puntas hacia fuera, desciende manteniendo el torso vertical y las rodillas alineadas con los pies.",
    mistakes: "Rodillas colapsando hacia dentro al subir.",
  },
  {
    slug: "single-leg-leg-press",
    name: "Single-Leg Leg Press",
    difficulty: "intermediate",
    pattern: "squat",
    primary: ["quadriceps", "glutes"],
    secondary: [],
    equipment: ["gym_machine"],
    instructions: "Con un solo pie en la plataforma, empuja controlando el descenso sin que la rodilla colapse hacia dentro.",
    mistakes: "Compensar con el otro lado del cuerpo en vez de estabilizar con la pierna activa.",
  },
  {
    slug: "adductor-machine",
    name: "Adductor Machine",
    difficulty: "beginner",
    pattern: "squat",
    primary: ["quadriceps"],
    secondary: [],
    equipment: ["gym_machine"],
    instructions: "Sentado con las piernas abiertas en los apoyos, junta las piernas contrayendo la cara interna del muslo.",
    mistakes: "Usar un rango de movimiento demasiado rápido sin control.",
  },
  {
    slug: "abductor-machine",
    name: "Abductor Machine",
    difficulty: "beginner",
    pattern: "squat",
    primary: ["glutes"],
    secondary: [],
    equipment: ["gym_machine"],
    instructions: "Sentado con las piernas juntas en los apoyos, separa las piernas contrayendo el glúteo medio.",
    mistakes: "Inclinar la pelvis en vez de mantenerla fija durante la apertura.",
  },
  {
    slug: "nordic-hamstring-curl",
    name: "Nordic Hamstring Curl",
    difficulty: "advanced",
    pattern: "hinge",
    primary: ["hamstrings"],
    secondary: ["glutes"],
    equipment: [],
    instructions: "Con los tobillos fijados, desciende el torso hacia el suelo con control usando solo la fuerza de los isquios.",
    mistakes: "Flexionar la cadera durante la caída en vez de mantener el cuerpo en línea recta.",
  },
  {
    slug: "stiff-leg-deadlift",
    name: "Stiff-Leg Deadlift",
    difficulty: "intermediate",
    pattern: "hinge",
    primary: ["hamstrings"],
    secondary: ["glutes", "back"],
    equipment: ["barbell"],
    instructions: "Con las rodillas casi extendidas, baja la barra pegada a las piernas mediante bisagra de cadera pura.",
    mistakes: "Flexionar las rodillas convirtiéndolo en un peso muerto convencional.",
  },
  {
    slug: "single-leg-romanian-deadlift",
    name: "Single-Leg Romanian Deadlift",
    difficulty: "advanced",
    pattern: "hinge",
    primary: ["hamstrings", "glutes"],
    secondary: ["core"],
    equipment: ["dumbbells"],
    instructions: "Apoyado en una pierna, inclina el torso hacia delante elevando la otra pierna en línea con la espalda.",
    mistakes: "Rotar la cadera en vez de mantenerla cuadrada al suelo.",
  },
  {
    slug: "deficit-deadlift",
    name: "Deficit Deadlift",
    difficulty: "advanced",
    pattern: "hinge",
    primary: ["hamstrings", "back"],
    secondary: ["glutes"],
    equipment: ["barbell"],
    instructions: "De pie sobre una plataforma elevada, levanta la barra desde un rango de movimiento mayor manteniendo la espalda neutra.",
    mistakes: "Redondear la espalda baja por el mayor rango de movimiento.",
  },
  {
    slug: "cable-pull-through",
    name: "Cable Pull-Through",
    difficulty: "beginner",
    pattern: "hinge",
    primary: ["glutes", "hamstrings"],
    secondary: ["core"],
    equipment: ["cable_machine"],
    instructions: "De espaldas a la polea baja, realiza una bisagra de cadera y extiende empujando la cadera al frente.",
    mistakes: "Flexionar las rodillas en vez de mover la cadera hacia atrás.",
  },
  {
    slug: "cable-glute-kickback",
    name: "Cable Glute Kickback",
    difficulty: "beginner",
    pattern: "hinge",
    primary: ["glutes"],
    secondary: ["hamstrings"],
    equipment: ["cable_machine"],
    instructions: "Con el tobillo enganchado al cable, extiende la cadera llevando la pierna hacia atrás sin arquear la espalda.",
    mistakes: "Usar impulso lumbar en vez de aislar el glúteo.",
  },
  {
    slug: "curtsy-lunge",
    name: "Curtsy Lunge",
    difficulty: "intermediate",
    pattern: "locomotion",
    primary: ["glutes", "quadriceps"],
    secondary: ["hamstrings"],
    equipment: [],
    instructions: "Cruza una pierna por detrás en diagonal y desciende flexionando ambas rodillas, manteniendo el torso erguido.",
    mistakes: "Perder el equilibrio por dar un paso demasiado corto.",
  },
  {
    slug: "lateral-lunge",
    name: "Lateral Lunge",
    difficulty: "intermediate",
    pattern: "locomotion",
    primary: ["glutes", "quadriceps"],
    secondary: ["hamstrings"],
    equipment: [],
    instructions: "Da un paso amplio hacia un lado y flexiona esa rodilla manteniendo la otra pierna extendida.",
    mistakes: "Adelantar el torso perdiendo la carga en el glúteo de la pierna flexionada.",
  },
  {
    slug: "seated-calf-raise",
    name: "Seated Calf Raise",
    difficulty: "beginner",
    pattern: "squat",
    primary: ["calves"],
    secondary: [],
    equipment: ["gym_machine"],
    instructions: "Sentado con las rodillas bajo el cojín, eleva los talones contrayendo el gemelo al máximo.",
    mistakes: "Recorrido parcial sin bajar completamente el talón.",
  },
  {
    slug: "leg-press-calf-raise",
    name: "Leg Press Calf Raise",
    difficulty: "beginner",
    pattern: "squat",
    primary: ["calves"],
    secondary: [],
    equipment: ["gym_machine"],
    instructions: "Con las piernas extendidas en la prensa, empuja la plataforma solo con la punta del pie.",
    mistakes: "Mantener las rodillas flexionadas, quitando tensión al gemelo.",
  },
  {
    slug: "donkey-calf-raise",
    name: "Donkey Calf Raise",
    difficulty: "intermediate",
    pattern: "squat",
    primary: ["calves"],
    secondary: [],
    equipment: ["gym_machine"],
    instructions: "Con el torso inclinado hacia delante, eleva los talones contrayendo el gemelo en todo el recorrido.",
    mistakes: "Rebotar entre repeticiones en vez de controlar el descenso.",
  },
  {
    slug: "jefferson-curl",
    name: "Jefferson Curl",
    difficulty: "advanced",
    pattern: "hinge",
    primary: ["hamstrings", "back"],
    secondary: ["core"],
    equipment: ["plate"],
    instructions: "De pie sobre una superficie elevada, enrolla la columna vértebra a vértebra bajando el peso hacia el suelo con control.",
    mistakes: "Ejecutar el movimiento con demasiada velocidad sin control vertebral.",
  },
  {
    slug: "banded-hip-abduction",
    name: "Banded Hip Abduction",
    difficulty: "beginner",
    pattern: "squat",
    primary: ["glutes"],
    secondary: [],
    equipment: ["resistance_band"],
    instructions: "Con la banda alrededor de las rodillas, separa las rodillas contra la resistencia manteniendo la cadera fija.",
    mistakes: "Balancear la cadera en vez de aislar el movimiento en la pierna.",
  },
  {
    slug: "monster-walk",
    name: "Monster Walk",
    difficulty: "beginner",
    pattern: "locomotion",
    primary: ["glutes"],
    secondary: ["quadriceps"],
    equipment: ["resistance_band"],
    instructions: "Con la banda en los tobillos, camina lateralmente manteniendo tensión constante en la banda.",
    mistakes: "Pasos demasiado pequeños que reducen la activación del glúteo.",
  },
];

export default exercises;
