// Plyometrics -- box-jump and burpee already exist.
const exercises = [
  {
    slug: "broad-jump",
    name: "Broad Jump",
    difficulty: "intermediate",
    pattern: "locomotion",
    primary: ["quadriceps", "glutes"],
    secondary: ["calves"],
    equipment: [],
    instructions: "Desde parado, salta lo más lejos posible al frente aterrizando con ambos pies y control.",
    mistakes: "Aterrizar con las rodillas bloqueadas en vez de amortiguar flexionando.",
  },
  {
    slug: "tuck-jump",
    name: "Tuck Jump",
    difficulty: "intermediate",
    pattern: "locomotion",
    primary: ["quadriceps", "glutes"],
    secondary: ["core"],
    equipment: [],
    instructions: "Salta verticalmente llevando ambas rodillas hacia el pecho en el punto más alto del salto.",
    mistakes: "Aterrizar con poca flexión de rodilla, absorbiendo mal el impacto.",
  },
  {
    slug: "squat-jump",
    name: "Squat Jump",
    difficulty: "intermediate",
    pattern: "squat",
    primary: ["quadriceps", "glutes"],
    secondary: ["calves"],
    equipment: [],
    instructions: "Desde la posición baja de sentadilla, salta explosivamente hacia arriba y aterriza volviendo a la posición baja.",
    mistakes: "Rodillas colapsando hacia dentro en el aterrizaje.",
  },
  {
    slug: "split-jump",
    name: "Split Jump",
    difficulty: "intermediate",
    pattern: "locomotion",
    primary: ["quadriceps", "glutes"],
    secondary: ["calves"],
    equipment: [],
    instructions: "Desde una posición de zancada, salta alternando la pierna delantera en el aire y aterriza en zancada.",
    mistakes: "Aterrizar con el torso inclinado hacia delante en vez de erguido.",
  },
  {
    slug: "depth-jump",
    name: "Depth Jump",
    difficulty: "advanced",
    pattern: "locomotion",
    primary: ["quadriceps", "glutes"],
    secondary: ["calves"],
    equipment: ["box"],
    instructions: "Baja de un cajón y, al tocar el suelo, salta inmediatamente lo más alto posible minimizando el tiempo de contacto.",
    mistakes: "Pausar demasiado en el suelo antes de saltar, perdiendo el efecto pliométrico.",
  },
  {
    slug: "lateral-bound",
    name: "Lateral Bound",
    difficulty: "intermediate",
    pattern: "locomotion",
    primary: ["glutes", "quadriceps"],
    secondary: ["calves"],
    equipment: [],
    instructions: "Salta lateralmente de una pierna hacia la otra amortiguando el aterrizaje con control antes de repetir.",
    mistakes: "Aterrizar con la rodilla colapsando hacia dentro.",
  },
  {
    slug: "skater-jump",
    name: "Skater Jump",
    difficulty: "intermediate",
    pattern: "locomotion",
    primary: ["glutes", "quadriceps"],
    secondary: ["calves"],
    equipment: [],
    instructions: "Salta lateralmente llevando la pierna trasera por detrás en cada aterrizaje, como el patinaje de velocidad.",
    mistakes: "Perder el equilibrio por aterrizar con el pie demasiado adelantado.",
  },
  {
    slug: "plyo-push-up",
    name: "Plyo Push Up",
    difficulty: "advanced",
    pattern: "push",
    primary: ["chest", "shoulders"],
    secondary: ["triceps", "core"],
    equipment: [],
    instructions: "Empuja con fuerza suficiente para que las manos despeguen del suelo y aterriza amortiguando con los codos.",
    mistakes: "Aterrizar con los codos completamente bloqueados en vez de amortiguar.",
  },
  {
    slug: "box-step-down",
    name: "Box Step-Down",
    difficulty: "beginner",
    pattern: "locomotion",
    primary: ["quadriceps", "glutes"],
    secondary: ["calves"],
    equipment: ["box"],
    instructions: "De pie sobre el cajón, desciende con una pierna con control hasta tocar el suelo con el talón.",
    mistakes: "Dejarse caer sin control en vez de bajar de forma controlada.",
  },
  {
    slug: "single-leg-box-jump",
    name: "Single-Leg Box Jump",
    difficulty: "advanced",
    pattern: "locomotion",
    primary: ["quadriceps", "glutes"],
    secondary: ["calves", "core"],
    equipment: ["box"],
    instructions: "Desde apoyo en una sola pierna, salta al cajón aterrizando con la misma pierna con control.",
    mistakes: "Usar impulso excesivo del brazo contrario en vez de fuerza de la pierna.",
  },
];

export default exercises;
