// Shoulders -- presses, raises, rear-delt work not already in the catalog.
export default [
  {
    slug: "arnold-press",
    name: "Arnold Press",
    difficulty: "intermediate",
    pattern: "push",
    primary: ["shoulders"],
    secondary: ["triceps"],
    equipment: ["dumbbells"],
    instructions: "Empieza con las palmas hacia ti y rota las muñecas hacia fuera mientras empujas las mancuernas por encima de la cabeza.",
    mistakes: "Arquear la espalda baja para completar la extensión.",
  },
  {
    slug: "seated-dumbbell-shoulder-press",
    name: "Seated Dumbbell Shoulder Press",
    difficulty: "beginner",
    pattern: "push",
    primary: ["shoulders"],
    secondary: ["triceps"],
    equipment: ["dumbbells", "bench"],
    instructions: "Sentado con respaldo, empuja ambas mancuernas desde la altura del hombro hasta la extensión completa.",
    mistakes: "Chocar las mancuernas arriba perdiendo tensión en el hombro.",
  },
  {
    slug: "machine-shoulder-press",
    name: "Machine Shoulder Press",
    difficulty: "beginner",
    pattern: "push",
    primary: ["shoulders"],
    secondary: ["triceps"],
    equipment: ["gym_machine"],
    instructions: "Ajusta el asiento para que los manillares queden a la altura del hombro y empuja hacia arriba.",
    mistakes: "Asiento demasiado bajo, forzando un rango de movimiento incómodo.",
  },
  {
    slug: "upright-row",
    name: "Upright Row",
    difficulty: "intermediate",
    pattern: "pull",
    primary: ["shoulders"],
    secondary: ["back", "forearms"],
    equipment: ["barbell"],
    instructions: "Tira de la barra verticalmente pegada al cuerpo hasta la altura del pecho, guiando con los codos.",
    mistakes: "Elevar la barra por encima de la altura del hombro.",
  },
  {
    slug: "cable-lateral-raise",
    name: "Cable Lateral Raise",
    difficulty: "beginner",
    pattern: "push",
    primary: ["shoulders"],
    secondary: [],
    equipment: ["cable_machine"],
    instructions: "Con la polea baja a un lado, eleva el brazo lateralmente hasta la altura del hombro con codo ligeramente flexionado.",
    mistakes: "Usar impulso del torso para elevar el cable.",
  },
  {
    slug: "cable-front-raise",
    name: "Cable Front Raise",
    difficulty: "beginner",
    pattern: "push",
    primary: ["shoulders"],
    secondary: [],
    equipment: ["cable_machine"],
    instructions: "Con la polea baja al frente, eleva el brazo hacia delante hasta la altura del hombro sin balancear el torso.",
    mistakes: "Elevar el brazo por encima de la altura del hombro.",
  },
  {
    slug: "reverse-fly-machine",
    name: "Reverse Fly Machine",
    difficulty: "beginner",
    pattern: "pull",
    primary: ["shoulders"],
    secondary: ["back"],
    equipment: ["gym_machine"],
    instructions: "Pecho apoyado en el respaldo, abre los brazos hacia atrás contrayendo la parte posterior del hombro.",
    mistakes: "Encoger los hombros en vez de mantenerlos bajos durante la apertura.",
  },
  {
    slug: "dumbbell-reverse-fly",
    name: "Dumbbell Reverse Fly",
    difficulty: "beginner",
    pattern: "pull",
    primary: ["shoulders"],
    secondary: ["back"],
    equipment: ["dumbbells"],
    instructions: "Inclinado hacia delante con las mancuernas colgando, abre los brazos lateralmente contrayendo la espalda alta.",
    mistakes: "Flexionar demasiado el codo, convirtiéndolo en un remo.",
  },
  {
    slug: "plate-front-raise",
    name: "Plate Front Raise",
    difficulty: "beginner",
    pattern: "push",
    primary: ["shoulders"],
    secondary: [],
    equipment: ["plate"],
    instructions: "Sujeta el disco con ambas manos y elévalo al frente hasta la altura de los ojos con los brazos casi extendidos.",
    mistakes: "Balancear el torso hacia atrás para ayudar a elevar el disco.",
  },
  {
    slug: "cuban-press",
    name: "Cuban Press",
    difficulty: "advanced",
    pattern: "push",
    primary: ["shoulders"],
    secondary: ["back"],
    equipment: ["dumbbells"],
    instructions: "Desde la posición de remo al alto, rota los brazos hacia arriba y empuja las mancuernas hasta la extensión completa.",
    mistakes: "Saltarse la fase de rotación externa entre remo y press.",
  },
  {
    slug: "pike-shoulder-press",
    name: "Pike Shoulder Press",
    difficulty: "intermediate",
    pattern: "push",
    primary: ["shoulders"],
    secondary: ["triceps", "core"],
    equipment: [],
    instructions: "En posición de V invertida con la cadera elevada, flexiona los codos bajando la cabeza hacia el suelo y empuja de vuelta.",
    mistakes: "Perder la posición de cadera elevada durante el descenso.",
  },
];
