-- Exercise catalog expansion: idempotent bulk seed generated from
-- supabase/seed/exercises/*.mjs -- see supabase/seed/README.md.
-- Safe to re-run: every insert is `on conflict do nothing`.

-- New equipment slugs (data only, no schema change) ------------------
insert into public.equipment (slug, name) values
  ('plate', 'Discos'),
  ('suspension_trainer', 'TRX / Suspensión'),
  ('box', 'Cajón pliométrico'),
  ('ab_wheel', 'Rueda abdominal'),
  ('other', 'Otro')
on conflict (slug) do nothing;

-- Exercises -------------------------------------------------------------
insert into public.exercises (slug, name, difficulty, movement_pattern, primary_muscles, secondary_muscles, instructions, common_mistakes) values
  ('decline-barbell-bench-press', 'Decline Barbell Bench Press', 'intermediate', 'push', array['chest']::text[], array['triceps']::text[], 'En banco declinado, baja la barra hasta la parte baja del pecho y empuja a extensión completa.', 'Recorrido demasiado corto por miedo a golpear el pecho.'),
  ('decline-dumbbell-press', 'Decline Dumbbell Press', 'intermediate', 'push', array['chest']::text[], array['triceps']::text[], 'En banco declinado, empuja ambas mancuernas desde el pecho hasta la extensión completa de brazos.', 'Chocar las mancuernas antes de completar el bloqueo de codo.'),
  ('incline-dumbbell-press', 'Incline Dumbbell Press', 'intermediate', 'push', array['chest']::text[], array['shoulders', 'triceps']::text[], 'En banco inclinado a 30-45°, empuja las mancuernas desde la altura del pecho superior hasta arriba.', 'Inclinación excesiva del banco, convirtiéndolo en press de hombro.'),
  ('close-grip-bench-press', 'Close Grip Bench Press', 'intermediate', 'push', array['triceps']::text[], array['chest']::text[], 'Agarre a la anchura de hombros, baja la barra al pecho manteniendo los codos cerca del cuerpo y empuja.', 'Agarre demasiado estrecho que sobrecarga la muñeca.'),
  ('svend-press', 'Svend Press', 'beginner', 'push', array['chest']::text[], array['shoulders']::text[], 'Presiona dos discos entre las palmas a la altura del pecho y empuja al frente sin separarlos.', 'Perder la presión entre los discos durante el movimiento.'),
  ('floor-press', 'Floor Press', 'intermediate', 'push', array['chest']::text[], array['triceps']::text[], 'Tumbado en el suelo, baja la barra hasta que los tríceps toquen el suelo y empuja a extensión completa.', 'Rebotar los codos contra el suelo en vez de controlar el descenso.'),
  ('dumbbell-fly', 'Dumbbell Fly', 'beginner', 'push', array['chest']::text[], array['shoulders']::text[], 'Tumbado en banco plano, abre los brazos con codos ligeramente flexionados y junta las mancuernas sobre el pecho.', 'Flexionar completamente el codo convirtiéndolo en un press.'),
  ('incline-dumbbell-fly', 'Incline Dumbbell Fly', 'intermediate', 'push', array['chest']::text[], array['shoulders']::text[], 'En banco inclinado, abre los brazos y junta las mancuernas por encima del pecho superior con codos semiflexionados.', 'Bajar demasiado provocando tensión excesiva en el hombro.'),
  ('cable-fly-low-to-high', 'Cable Fly (Low to High)', 'intermediate', 'push', array['chest']::text[], array['shoulders']::text[], 'Poleas bajas, tira ambos cables en diagonal hacia arriba juntando las manos frente al pecho superior.', 'Usar solo los brazos sin cerrar el pecho al final del recorrido.'),
  ('cable-fly-high-to-low', 'Cable Fly (High to Low)', 'intermediate', 'push', array['chest']::text[], array['shoulders']::text[], 'Poleas altas, tira ambos cables en diagonal hacia abajo juntando las manos frente a la cadera.', 'Curvar la espalda para ganar recorrido en vez de controlar con el pecho.'),
  ('chest-press-machine', 'Chest Press Machine', 'beginner', 'push', array['chest']::text[], array['triceps', 'shoulders']::text[], 'Ajusta el asiento a la altura del pecho y empuja los manillares hasta extensión sin bloquear violentamente el codo.', 'Asiento demasiado bajo o alto, cambiando el ángulo de empuje.'),
  ('pec-deck', 'Pec Deck', 'beginner', 'push', array['chest']::text[], array[]::text[], 'Antebrazos apoyados en los cojines, junta los brazos al frente contrayendo el pecho.', 'Impulsar con los hombros en vez de cerrar con el pecho.'),
  ('decline-push-up', 'Decline Push Up', 'intermediate', 'push', array['chest', 'shoulders']::text[], array['triceps', 'core']::text[], 'Pies elevados sobre un banco, realiza la flexión manteniendo el cuerpo en línea recta.', 'Cadera caída por falta de tensión en el core.'),
  ('archer-push-up', 'Archer Push Up', 'advanced', 'push', array['chest', 'triceps']::text[], array['shoulders', 'core']::text[], 'Manos muy separadas, desplaza el peso hacia un lado flexionando ese codo mientras el otro brazo queda extendido.', 'Rotar la cadera en vez de mantenerla cuadrada al suelo.'),
  ('hindu-push-up', 'Hindu Push Up', 'intermediate', 'push', array['chest', 'shoulders']::text[], array['core']::text[], 'Desde posición de V invertida, desciende la cadera en arco pasando cerca del suelo hasta terminar con el pecho elevado.', 'Cortar el recorrido en arco en vez de deslizar todo el cuerpo.'),
  ('seated-cable-row', 'Seated Cable Row', 'beginner', 'pull', array['back', 'lats']::text[], array['biceps', 'forearms']::text[], 'Sentado con rodillas ligeramente flexionadas, tira del agarre hacia el abdomen manteniendo la espalda recta.', 'Balancear el torso hacia atrás para ayudar a tirar del peso.'),
  ('single-arm-dumbbell-row', 'Single-Arm Dumbbell Row', 'beginner', 'pull', array['back', 'lats']::text[], array['biceps', 'forearms']::text[], 'Apoya rodilla y mano en el banco, tira de la mancuerna hacia la cadera manteniendo el torso paralelo al suelo.', 'Rotar el torso para ganar recorrido en vez de tirar solo con el brazo.'),
  ('chest-supported-row', 'Chest-Supported Row', 'beginner', 'pull', array['back']::text[], array['biceps']::text[], 'Tumbado boca abajo sobre un banco inclinado, tira de las mancuernas hacia la cadera sin usar impulso.', 'Despegar el pecho del banco para generar impulso.'),
  ('t-bar-row', 'T-Bar Row', 'intermediate', 'pull', array['back']::text[], array['biceps', 'forearms']::text[], 'Con el torso inclinado y la barra entre las piernas, tira del agarre hacia el pecho contrayendo la espalda.', 'Extender la espalda baja en vez de mantenerla neutra durante la tracción.'),
  ('machine-row', 'Machine Row', 'beginner', 'pull', array['back']::text[], array['biceps']::text[], 'Pecho apoyado en el respaldo, tira de los manillares hacia atrás contrayendo los omóplatos.', 'Usar solo los brazos sin retraer la escápula.'),
  ('straight-arm-pulldown', 'Straight-Arm Pulldown', 'intermediate', 'pull', array['lats']::text[], array['core']::text[], 'Con los brazos extendidos, tira de la barra hacia los muslos manteniendo un ligero doblez de codo constante.', 'Flexionar el codo durante el descenso, convirtiéndolo en un press.'),
  ('dumbbell-pullover', 'Dumbbell Pullover', 'intermediate', 'pull', array['lats', 'chest']::text[], array['core']::text[], 'Tumbado perpendicular al banco, baja la mancuerna en arco por detrás de la cabeza y vuelve a subirla sobre el pecho.', 'Arquear excesivamente la espalda baja durante el descenso.'),
  ('wide-grip-lat-pulldown', 'Wide-Grip Lat Pulldown', 'beginner', 'pull', array['lats']::text[], array['biceps']::text[], 'Agarre ancho, tira de la barra hacia la parte alta del pecho manteniendo el torso ligeramente inclinado hacia atrás.', 'Tirar de la barra por detrás de la nuca.'),
  ('close-grip-lat-pulldown', 'Close-Grip Lat Pulldown', 'beginner', 'pull', array['lats']::text[], array['biceps']::text[], 'Agarre estrecho neutro, tira de la barra hacia el pecho contrayendo la espalda al final del recorrido.', 'Recorrido parcial sin extender completamente los brazos al subir.'),
  ('barbell-shrug', 'Barbell Shrug', 'beginner', 'pull', array['back']::text[], array['forearms']::text[], 'Sujeta la barra con los brazos extendidos y eleva los hombros directamente hacia arriba sin flexionar el codo.', 'Rotar los hombros en vez de elevarlos en línea recta.'),
  ('dumbbell-shrug', 'Dumbbell Shrug', 'beginner', 'pull', array['back']::text[], array['forearms']::text[], 'Con una mancuerna en cada mano, eleva los hombros directamente hacia arriba y controla el descenso.', 'Usar impulso de las piernas para ayudar a elevar el peso.'),
  ('good-morning', 'Good Morning', 'advanced', 'hinge', array['hamstrings', 'back']::text[], array['glutes']::text[], 'Barra sobre los trapecios, inclina el torso hacia delante con bisagra de cadera manteniendo las rodillas casi extendidas.', 'Redondear la espalda baja en vez de mantenerla neutra.'),
  ('landmine-row', 'Landmine Row', 'intermediate', 'pull', array['back']::text[], array['biceps']::text[], 'Con un extremo de la barra anclado, tira del otro extremo hacia el torso manteniendo la espalda neutra.', 'Extender la espalda baja para ayudar a tirar del peso.'),
  ('renegade-row', 'Renegade Row', 'advanced', 'pull', array['back', 'core']::text[], array['shoulders']::text[], 'En posición de plancha con las manos sobre mancuernas, tira alternando un brazo hacia la cadera manteniendo la cadera estable.', 'Rotar la cadera hacia el lado que tira en vez de mantenerla cuadrada.'),
  ('rack-pull', 'Rack Pull', 'intermediate', 'hinge', array['back', 'hamstrings']::text[], array['glutes', 'forearms']::text[], 'Desde soportes a la altura de la rodilla, levanta la barra extendiendo cadera y rodillas hasta quedar erguido.', 'Empezar con la espalda redondeada por la altura reducida del recorrido.'),
  ('sumo-deadlift', 'Sumo Deadlift', 'intermediate', 'hinge', array['glutes', 'hamstrings']::text[], array['back', 'quadriceps']::text[], 'Pies muy separados y puntas hacia fuera, levanta la barra manteniéndola pegada al cuerpo con el torso más vertical.', 'Rodillas colapsando hacia dentro durante el tirón.'),
  ('arnold-press', 'Arnold Press', 'intermediate', 'push', array['shoulders']::text[], array['triceps']::text[], 'Empieza con las palmas hacia ti y rota las muñecas hacia fuera mientras empujas las mancuernas por encima de la cabeza.', 'Arquear la espalda baja para completar la extensión.'),
  ('seated-dumbbell-shoulder-press', 'Seated Dumbbell Shoulder Press', 'beginner', 'push', array['shoulders']::text[], array['triceps']::text[], 'Sentado con respaldo, empuja ambas mancuernas desde la altura del hombro hasta la extensión completa.', 'Chocar las mancuernas arriba perdiendo tensión en el hombro.'),
  ('machine-shoulder-press', 'Machine Shoulder Press', 'beginner', 'push', array['shoulders']::text[], array['triceps']::text[], 'Ajusta el asiento para que los manillares queden a la altura del hombro y empuja hacia arriba.', 'Asiento demasiado bajo, forzando un rango de movimiento incómodo.'),
  ('upright-row', 'Upright Row', 'intermediate', 'pull', array['shoulders']::text[], array['back', 'forearms']::text[], 'Tira de la barra verticalmente pegada al cuerpo hasta la altura del pecho, guiando con los codos.', 'Elevar la barra por encima de la altura del hombro.'),
  ('cable-lateral-raise', 'Cable Lateral Raise', 'beginner', 'push', array['shoulders']::text[], array[]::text[], 'Con la polea baja a un lado, eleva el brazo lateralmente hasta la altura del hombro con codo ligeramente flexionado.', 'Usar impulso del torso para elevar el cable.'),
  ('cable-front-raise', 'Cable Front Raise', 'beginner', 'push', array['shoulders']::text[], array[]::text[], 'Con la polea baja al frente, eleva el brazo hacia delante hasta la altura del hombro sin balancear el torso.', 'Elevar el brazo por encima de la altura del hombro.'),
  ('reverse-fly-machine', 'Reverse Fly Machine', 'beginner', 'pull', array['shoulders']::text[], array['back']::text[], 'Pecho apoyado en el respaldo, abre los brazos hacia atrás contrayendo la parte posterior del hombro.', 'Encoger los hombros en vez de mantenerlos bajos durante la apertura.'),
  ('dumbbell-reverse-fly', 'Dumbbell Reverse Fly', 'beginner', 'pull', array['shoulders']::text[], array['back']::text[], 'Inclinado hacia delante con las mancuernas colgando, abre los brazos lateralmente contrayendo la espalda alta.', 'Flexionar demasiado el codo, convirtiéndolo en un remo.'),
  ('plate-front-raise', 'Plate Front Raise', 'beginner', 'push', array['shoulders']::text[], array[]::text[], 'Sujeta el disco con ambas manos y elévalo al frente hasta la altura de los ojos con los brazos casi extendidos.', 'Balancear el torso hacia atrás para ayudar a elevar el disco.'),
  ('cuban-press', 'Cuban Press', 'advanced', 'push', array['shoulders']::text[], array['back']::text[], 'Desde la posición de remo al alto, rota los brazos hacia arriba y empuja las mancuernas hasta la extensión completa.', 'Saltarse la fase de rotación externa entre remo y press.'),
  ('pike-shoulder-press', 'Pike Shoulder Press', 'intermediate', 'push', array['shoulders']::text[], array['triceps', 'core']::text[], 'En posición de V invertida con la cadera elevada, flexiona los codos bajando la cabeza hacia el suelo y empuja de vuelta.', 'Perder la posición de cadera elevada durante el descenso.'),
  ('barbell-curl', 'Barbell Curl', 'beginner', 'pull', array['biceps']::text[], array['forearms']::text[], 'De pie, flexiona los codos elevando la barra hasta la altura del hombro sin mover el torso.', 'Balancear la cadera para generar impulso.'),
  ('ez-bar-curl', 'EZ-Bar Curl', 'beginner', 'pull', array['biceps']::text[], array['forearms']::text[], 'Con la barra Z, flexiona los codos elevando el peso manteniendo los codos pegados al torso.', 'Abrir los codos hacia fuera durante la subida.'),
  ('dumbbell-curl', 'Dumbbell Curl', 'beginner', 'pull', array['biceps']::text[], array['forearms']::text[], 'De pie, flexiona alternando o a la vez los codos elevando las mancuernas hasta el hombro.', 'Rotar el hombro hacia delante para ayudar a subir el peso.'),
  ('hammer-curl', 'Hammer Curl', 'beginner', 'pull', array['biceps', 'forearms']::text[], array[]::text[], 'Con agarre neutro (palmas encaradas), flexiona los codos elevando las mancuernas sin rotar la muñeca.', 'Usar impulso del hombro en vez de flexión pura de codo.'),
  ('incline-dumbbell-curl', 'Incline Dumbbell Curl', 'intermediate', 'pull', array['biceps']::text[], array[]::text[], 'Sentado en banco inclinado con los brazos colgando, flexiona los codos manteniendo los hombros hacia atrás.', 'Adelantar el hombro perdiendo el estiramiento del bíceps.'),
  ('preacher-curl', 'Preacher Curl', 'intermediate', 'pull', array['biceps']::text[], array[]::text[], 'Con el brazo apoyado en el banco predicador, flexiona el codo sin despegar el tríceps del apoyo.', 'Extender completamente el codo de golpe al bajar el peso.'),
  ('concentration-curl', 'Concentration Curl', 'beginner', 'pull', array['biceps']::text[], array[]::text[], 'Sentado, apoya el codo en la cara interna del muslo y flexiona la mancuerna hacia el hombro.', 'Mover el codo del punto de apoyo durante la repetición.'),
  ('cable-curl', 'Cable Curl', 'beginner', 'pull', array['biceps']::text[], array['forearms']::text[], 'Con la polea baja, flexiona los codos tirando de la barra hacia el hombro sin mover el torso.', 'Inclinar el torso hacia atrás para ayudar a subir el peso.'),
  ('reverse-curl', 'Reverse Curl', 'intermediate', 'pull', array['forearms', 'biceps']::text[], array[]::text[], 'Con agarre prono (palmas hacia abajo), flexiona los codos elevando la barra hasta la altura del hombro.', 'Usar peso excesivo que obliga a compensar con la muñeca.'),
  ('drag-curl', 'Drag Curl', 'intermediate', 'pull', array['biceps']::text[], array[]::text[], 'Mantén la barra pegada al cuerpo mientras flexionas el codo, llevando el codo hacia atrás en vez de adelante.', 'Separar la barra del cuerpo convirtiéndolo en un curl estándar.'),
  ('triceps-pushdown', 'Triceps Pushdown', 'beginner', 'push', array['triceps']::text[], array[]::text[], 'Con la polea alta, extiende los codos empujando la barra hacia abajo sin despegar los codos del torso.', 'Separar los codos del cuerpo durante la extensión.'),
  ('overhead-triceps-extension', 'Overhead Triceps Extension', 'intermediate', 'push', array['triceps']::text[], array[]::text[], 'Con la mancuerna sujeta por encima de la cabeza, flexiona los codos bajándola detrás de la cabeza y extiende de vuelta.', 'Abrir los codos hacia los lados en vez de mantenerlos apuntando al frente.'),
  ('skull-crusher', 'Skull Crusher', 'intermediate', 'push', array['triceps']::text[], array[]::text[], 'Tumbado en banco, baja la barra hacia la frente flexionando solo el codo y extiende de vuelta.', 'Mover el hombro durante la flexión en vez de fijarlo.'),
  ('cable-overhead-extension', 'Cable Overhead Extension', 'intermediate', 'push', array['triceps']::text[], array[]::text[], 'De espaldas a la polea baja, extiende los codos por encima de la cabeza empujando la cuerda hacia arriba.', 'Arquear la espalda baja para ganar recorrido.'),
  ('dumbbell-kickback', 'Dumbbell Kickback', 'beginner', 'push', array['triceps']::text[], array[]::text[], 'Torso inclinado y brazo paralelo al suelo, extiende el codo llevando la mancuerna hacia atrás.', 'Bajar el brazo por debajo de la línea del torso durante la extensión.'),
  ('machine-triceps-extension', 'Machine Triceps Extension', 'beginner', 'push', array['triceps']::text[], array[]::text[], 'Codos apoyados en el cojín, extiende los antebrazos empujando los manillares hacia abajo.', 'Despegar los codos del apoyo durante la extensión.'),
  ('wrist-curl', 'Wrist Curl', 'beginner', 'pull', array['forearms']::text[], array[]::text[], 'Antebrazos apoyados en el muslo o banco, flexiona solo la muñeca elevando el peso.', 'Mover el codo en vez de aislar el movimiento en la muñeca.'),
  ('hack-squat', 'Hack Squat', 'intermediate', 'squat', array['quadriceps']::text[], array['glutes']::text[], 'Espalda apoyada en el respaldo inclinado, desciende flexionando rodillas hasta 90° y empuja de vuelta.', 'Despegar la zona lumbar del respaldo durante el descenso.'),
  ('sissy-squat', 'Sissy Squat', 'advanced', 'squat', array['quadriceps']::text[], array['core']::text[], 'Sujeto de un punto fijo, inclina el torso hacia atrás flexionando solo la rodilla mientras el cuerpo baja en línea recta.', 'Flexionar la cadera en vez de aislar el movimiento en la rodilla.'),
  ('sumo-squat', 'Sumo Squat', 'beginner', 'squat', array['glutes', 'quadriceps']::text[], array['hamstrings']::text[], 'Pies muy separados y puntas hacia fuera, desciende manteniendo el torso vertical y las rodillas alineadas con los pies.', 'Rodillas colapsando hacia dentro al subir.'),
  ('single-leg-leg-press', 'Single-Leg Leg Press', 'intermediate', 'squat', array['quadriceps', 'glutes']::text[], array[]::text[], 'Con un solo pie en la plataforma, empuja controlando el descenso sin que la rodilla colapse hacia dentro.', 'Compensar con el otro lado del cuerpo en vez de estabilizar con la pierna activa.'),
  ('adductor-machine', 'Adductor Machine', 'beginner', 'squat', array['quadriceps']::text[], array[]::text[], 'Sentado con las piernas abiertas en los apoyos, junta las piernas contrayendo la cara interna del muslo.', 'Usar un rango de movimiento demasiado rápido sin control.'),
  ('abductor-machine', 'Abductor Machine', 'beginner', 'squat', array['glutes']::text[], array[]::text[], 'Sentado con las piernas juntas en los apoyos, separa las piernas contrayendo el glúteo medio.', 'Inclinar la pelvis en vez de mantenerla fija durante la apertura.'),
  ('nordic-hamstring-curl', 'Nordic Hamstring Curl', 'advanced', 'hinge', array['hamstrings']::text[], array['glutes']::text[], 'Con los tobillos fijados, desciende el torso hacia el suelo con control usando solo la fuerza de los isquios.', 'Flexionar la cadera durante la caída en vez de mantener el cuerpo en línea recta.'),
  ('stiff-leg-deadlift', 'Stiff-Leg Deadlift', 'intermediate', 'hinge', array['hamstrings']::text[], array['glutes', 'back']::text[], 'Con las rodillas casi extendidas, baja la barra pegada a las piernas mediante bisagra de cadera pura.', 'Flexionar las rodillas convirtiéndolo en un peso muerto convencional.'),
  ('single-leg-romanian-deadlift', 'Single-Leg Romanian Deadlift', 'advanced', 'hinge', array['hamstrings', 'glutes']::text[], array['core']::text[], 'Apoyado en una pierna, inclina el torso hacia delante elevando la otra pierna en línea con la espalda.', 'Rotar la cadera en vez de mantenerla cuadrada al suelo.'),
  ('deficit-deadlift', 'Deficit Deadlift', 'advanced', 'hinge', array['hamstrings', 'back']::text[], array['glutes']::text[], 'De pie sobre una plataforma elevada, levanta la barra desde un rango de movimiento mayor manteniendo la espalda neutra.', 'Redondear la espalda baja por el mayor rango de movimiento.'),
  ('cable-pull-through', 'Cable Pull-Through', 'beginner', 'hinge', array['glutes', 'hamstrings']::text[], array['core']::text[], 'De espaldas a la polea baja, realiza una bisagra de cadera y extiende empujando la cadera al frente.', 'Flexionar las rodillas en vez de mover la cadera hacia atrás.'),
  ('cable-glute-kickback', 'Cable Glute Kickback', 'beginner', 'hinge', array['glutes']::text[], array['hamstrings']::text[], 'Con el tobillo enganchado al cable, extiende la cadera llevando la pierna hacia atrás sin arquear la espalda.', 'Usar impulso lumbar en vez de aislar el glúteo.'),
  ('curtsy-lunge', 'Curtsy Lunge', 'intermediate', 'locomotion', array['glutes', 'quadriceps']::text[], array['hamstrings']::text[], 'Cruza una pierna por detrás en diagonal y desciende flexionando ambas rodillas, manteniendo el torso erguido.', 'Perder el equilibrio por dar un paso demasiado corto.'),
  ('lateral-lunge', 'Lateral Lunge', 'intermediate', 'locomotion', array['glutes', 'quadriceps']::text[], array['hamstrings']::text[], 'Da un paso amplio hacia un lado y flexiona esa rodilla manteniendo la otra pierna extendida.', 'Adelantar el torso perdiendo la carga en el glúteo de la pierna flexionada.'),
  ('seated-calf-raise', 'Seated Calf Raise', 'beginner', 'squat', array['calves']::text[], array[]::text[], 'Sentado con las rodillas bajo el cojín, eleva los talones contrayendo el gemelo al máximo.', 'Recorrido parcial sin bajar completamente el talón.'),
  ('leg-press-calf-raise', 'Leg Press Calf Raise', 'beginner', 'squat', array['calves']::text[], array[]::text[], 'Con las piernas extendidas en la prensa, empuja la plataforma solo con la punta del pie.', 'Mantener las rodillas flexionadas, quitando tensión al gemelo.'),
  ('donkey-calf-raise', 'Donkey Calf Raise', 'intermediate', 'squat', array['calves']::text[], array[]::text[], 'Con el torso inclinado hacia delante, eleva los talones contrayendo el gemelo en todo el recorrido.', 'Rebotar entre repeticiones en vez de controlar el descenso.'),
  ('jefferson-curl', 'Jefferson Curl', 'advanced', 'hinge', array['hamstrings', 'back']::text[], array['core']::text[], 'De pie sobre una superficie elevada, enrolla la columna vértebra a vértebra bajando el peso hacia el suelo con control.', 'Ejecutar el movimiento con demasiada velocidad sin control vertebral.'),
  ('banded-hip-abduction', 'Banded Hip Abduction', 'beginner', 'squat', array['glutes']::text[], array[]::text[], 'Con la banda alrededor de las rodillas, separa las rodillas contra la resistencia manteniendo la cadera fija.', 'Balancear la cadera en vez de aislar el movimiento en la pierna.'),
  ('monster-walk', 'Monster Walk', 'beginner', 'locomotion', array['glutes']::text[], array['quadriceps']::text[], 'Con la banda en los tobillos, camina lateralmente manteniendo tensión constante en la banda.', 'Pasos demasiado pequeños que reducen la activación del glúteo.'),
  ('dead-bug', 'Dead Bug', 'beginner', 'core', array['core']::text[], array[]::text[], 'Tumbado boca arriba con brazos y piernas elevados, extiende brazo y pierna opuestos sin despegar la espalda baja del suelo.', 'Arquear la espalda baja al extender la pierna.'),
  ('bird-dog', 'Bird Dog', 'beginner', 'core', array['core']::text[], array['glutes', 'back']::text[], 'En cuadrupedia, extiende brazo y pierna opuestos manteniendo la cadera y los hombros nivelados.', 'Rotar la cadera al extender la pierna.'),
  ('ab-wheel-rollout', 'Ab Wheel Rollout', 'advanced', 'core', array['core']::text[], array['shoulders', 'lats']::text[], 'De rodillas, rueda la rueda hacia delante extendiendo el cuerpo y regresa contrayendo el abdomen sin arquear la espalda.', 'Dejar caer la cadera perdiendo la línea recta del cuerpo.'),
  ('cable-crunch', 'Cable Crunch', 'beginner', 'core', array['core']::text[], array[]::text[], 'De rodillas frente a la polea alta, flexiona el torso llevando los codos hacia las rodillas contrayendo el abdomen.', 'Mover solo los brazos en vez de flexionar la columna.'),
  ('reverse-crunch', 'Reverse Crunch', 'beginner', 'core', array['core']::text[], array[]::text[], 'Tumbado boca arriba, eleva la cadera del suelo llevando las rodillas hacia el pecho.', 'Usar impulso de las piernas en vez de contraer el abdomen inferior.'),
  ('bicycle-crunch', 'Bicycle Crunch', 'beginner', 'rotation', array['core']::text[], array[]::text[], 'Tumbado boca arriba, lleva el codo hacia la rodilla contraria alternando en un movimiento de pedaleo.', 'Tirar del cuello con las manos en vez de rotar el torso.'),
  ('mountain-climber', 'Mountain Climber', 'beginner', 'core', array['core']::text[], array['shoulders', 'quadriceps']::text[], 'En posición de plancha alta, lleva las rodillas alternando hacia el pecho manteniendo la cadera estable.', 'Elevar la cadera perdiendo la línea recta del cuerpo.'),
  ('pallof-press', 'Pallof Press', 'intermediate', 'rotation', array['core']::text[], array[]::text[], 'De pie lateral a la polea, empuja el agarre al frente resistiendo la rotación del torso hacia el cable.', 'Dejar que el torso rote hacia la polea durante el empuje.'),
  ('band-pallof-press', 'Band Pallof Press', 'beginner', 'rotation', array['core']::text[], array[]::text[], 'De pie lateral al anclaje de la banda, empuja el agarre al frente resistiendo la rotación del torso.', 'Dar un paso demasiado corto que reduce la tensión de la banda.'),
  ('woodchopper', 'Cable Woodchopper', 'intermediate', 'rotation', array['core']::text[], array['shoulders']::text[], 'Con la polea alta, tira del agarre en diagonal cruzando el cuerpo hasta la cadera contraria rotando el torso.', 'Mover solo los brazos en vez de rotar desde el torso.'),
  ('dragon-flag', 'Dragon Flag', 'advanced', 'core', array['core']::text[], array['back']::text[], 'Sujeto por detrás de la cabeza, eleva el cuerpo recto desde los hombros y baja con control sin tocar el banco.', 'Flexionar la cadera perdiendo la línea recta del cuerpo.'),
  ('knee-tuck', 'Knee Tuck', 'beginner', 'core', array['core']::text[], array[]::text[], 'Sentado con manos apoyadas a los lados, lleva las rodillas hacia el pecho y extiende de vuelta.', 'Balancear el torso en vez de aislar el movimiento en el abdomen.'),
  ('wide-grip-pull-up', 'Wide-Grip Pull Up', 'intermediate', 'pull', array['lats', 'back']::text[], array['biceps']::text[], 'Con agarre más ancho que los hombros, tira hasta que la barbilla supere la barra y baja con control.', 'Recorrido parcial por la mayor dificultad del agarre ancho.'),
  ('neutral-grip-pull-up', 'Neutral-Grip Pull Up', 'intermediate', 'pull', array['lats', 'back']::text[], array['biceps']::text[], 'Con agarre neutro (palmas encaradas), tira hasta que la barbilla supere las manos y baja con control.', 'Balanceo del cuerpo para ganar impulso.'),
  ('commando-pull-up', 'Commando Pull Up', 'advanced', 'pull', array['lats', 'back']::text[], array['biceps', 'core']::text[], 'Agarre con las manos una delante de otra, tira alternando el lado de la cabeza que pasa junto a la barra.', 'Rotar excesivamente el torso en vez de tirar en línea recta.'),
  ('archer-pull-up', 'Archer Pull Up', 'advanced', 'pull', array['lats', 'back']::text[], array['biceps']::text[], 'Agarre ancho, tira desplazando el peso hacia un lado mientras el otro brazo queda casi extendido.', 'No alcanzar suficiente altura para cargar realmente el lado activo.'),
  ('typewriter-pull-up', 'Typewriter Pull Up', 'advanced', 'pull', array['lats', 'back']::text[], array['biceps', 'core']::text[], 'Mantén la barbilla sobre la barra y desplaza el cuerpo lateralmente de un lado a otro sin bajar.', 'Perder la altura de la barbilla sobre la barra durante el desplazamiento.'),
  ('one-arm-pull-up-progression', 'One-Arm Pull Up Progression', 'advanced', 'pull', array['lats', 'back']::text[], array['biceps', 'core']::text[], 'Sujeta la muñeca del brazo activo con la mano libre para asistir parcialmente y tira con un solo brazo dominante.', 'Depender totalmente del brazo asistente en vez de cargar el brazo activo.'),
  ('l-sit-pull-up', 'L-Sit Pull Up', 'advanced', 'pull', array['lats', 'core']::text[], array['back', 'biceps']::text[], 'Manteniendo las piernas extendidas al frente en L, tira hasta que la barbilla supere la barra.', 'Dejar caer las piernas durante la tracción.'),
  ('ring-dip', 'Ring Dip', 'advanced', 'push', array['chest', 'triceps']::text[], array['shoulders']::text[], 'Sujeto en anillas, desciende controlando la estabilidad hasta 90° de codo y empuja de vuelta arriba.', 'Perder la estabilidad de las anillas por falta de control escapular.'),
  ('weighted-dip', 'Weighted Dip', 'advanced', 'push', array['chest', 'triceps']::text[], array['shoulders']::text[], 'Igual que el fondo estándar, con peso adicional mediante cinturón de lastre o mancuerna sujeta entre los pies.', 'Añadir peso antes de dominar el fondo estricto con buena técnica.'),
  ('spiderman-push-up', 'Spiderman Push Up', 'intermediate', 'push', array['chest', 'core']::text[], array['triceps']::text[], 'Durante la flexión, lleva una rodilla hacia el codo del mismo lado y alterna en cada repetición.', 'Rotar la cadera en vez de mantenerla cuadrada al suelo.'),
  ('one-arm-push-up', 'One-Arm Push Up', 'advanced', 'push', array['chest', 'triceps']::text[], array['core']::text[], 'Con los pies muy separados para estabilidad, realiza la flexión completa apoyando un solo brazo.', 'Rotar el torso hacia el lado que empuja en vez de mantenerlo cuadrado.'),
  ('pistol-squat', 'Pistol Squat', 'advanced', 'squat', array['quadriceps', 'glutes']::text[], array['core']::text[], 'Sobre una pierna, desciende manteniendo la otra pierna extendida al frente hasta profundidad completa y sube.', 'Perder el equilibrio hacia atrás al descender.'),
  ('shrimp-squat', 'Shrimp Squat', 'advanced', 'squat', array['quadriceps', 'glutes']::text[], array['core']::text[], 'Sobre una pierna, sujeta el tobillo contrario detrás del cuerpo y desciende hasta que la rodilla trasera casi toque el suelo.', 'Soltar el tobillo sujeto para facilitar el equilibrio.'),
  ('cossack-squat', 'Cossack Squat', 'intermediate', 'squat', array['quadriceps', 'glutes']::text[], array['hamstrings']::text[], 'Pies muy separados, desplaza el peso hacia un lado flexionando esa rodilla mientras la otra pierna queda extendida.', 'Despegar el talón de la pierna flexionada del suelo.'),
  ('front-lever-tuck', 'Front Lever Tuck', 'intermediate', 'core', array['lats', 'core']::text[], array['back']::text[], 'Colgado de la barra, lleva las rodillas al pecho y horizontaliza el cuerpo manteniendo los brazos extendidos.', 'Flexionar los codos para compensar la falta de fuerza en el dorsal.'),
  ('front-lever', 'Front Lever', 'advanced', 'core', array['lats', 'core']::text[], array['back']::text[], 'Colgado de la barra, mantén el cuerpo completamente horizontal y extendido con los brazos rectos.', 'Dejar caer la cadera por debajo de la línea del cuerpo.'),
  ('back-lever-tuck', 'Back Lever Tuck', 'advanced', 'core', array['lats', 'core']::text[], array['shoulders']::text[], 'Desde un agarre en pronación por detrás, invierte el cuerpo y mantén las rodillas encogidas horizontales bajo la barra.', 'Abrir los hombros en vez de mantener una rotación controlada.'),
  ('tuck-planche', 'Tuck Planche', 'advanced', 'core', array['shoulders', 'core']::text[], array['chest']::text[], 'Con las manos en el suelo y las rodillas encogidas al pecho, inclina los hombros al frente hasta despegar los pies.', 'No inclinar suficiente los hombros al frente, dejando peso en las manos sin despegar.'),
  ('handstand-hold', 'Handstand Hold', 'intermediate', 'core', array['shoulders', 'core']::text[], array['forearms']::text[], 'Con apoyo en la pared si es necesario, mantén el cuerpo invertido en línea recta con los brazos extendidos.', 'Arquear la espalda baja en vez de mantener el core activado.'),
  ('human-flag', 'Human Flag', 'advanced', 'core', array['lats', 'core']::text[], array['shoulders']::text[], 'Sujeto a un poste vertical con ambas manos, eleva el cuerpo horizontal lateral manteniéndolo recto.', 'Flexionar la cadera perdiendo la línea recta del cuerpo.'),
  ('kettlebell-clean', 'Kettlebell Clean', 'intermediate', 'hinge', array['hamstrings', 'glutes']::text[], array['shoulders', 'forearms']::text[], 'Con bisagra de cadera, lleva la kettlebell del suelo al hombro en un único movimiento fluido, recibiéndola en el antebrazo.', 'Golpear el antebrazo con la kettlebell por una trayectoria demasiado alejada del cuerpo.'),
  ('kettlebell-press', 'Kettlebell Press', 'intermediate', 'push', array['shoulders']::text[], array['triceps', 'core']::text[], 'Desde la posición de rack, empuja la kettlebell por encima de la cabeza hasta extensión completa del brazo.', 'Arquear la espalda baja para ayudar a completar el bloqueo.'),
  ('single-arm-kettlebell-press', 'Single-Arm Kettlebell Press', 'intermediate', 'push', array['shoulders']::text[], array['core']::text[], 'Desde el rack con un solo brazo, empuja la kettlebell arriba manteniendo el torso estable sin inclinarse lateralmente.', 'Inclinar el torso hacia el lado contrario para compensar el peso.'),
  ('kettlebell-row', 'Kettlebell Row', 'beginner', 'pull', array['back']::text[], array['biceps', 'forearms']::text[], 'Torso inclinado, tira de la kettlebell hacia la cadera manteniendo la espalda neutra.', 'Rotar el torso para ayudar a completar la tracción.'),
  ('kettlebell-goblet-lunge', 'Kettlebell Goblet Lunge', 'intermediate', 'locomotion', array['quadriceps', 'glutes']::text[], array['core']::text[], 'Sujetando la kettlebell contra el pecho, da un paso adelante y desciende hasta que ambas rodillas formen 90°.', 'Inclinar el torso hacia delante perdiendo la postura vertical.'),
  ('kettlebell-halo', 'Kettlebell Halo', 'beginner', 'rotation', array['shoulders']::text[], array['core']::text[], 'Sujeta la kettlebell por el asa invertida y rota alrededor de la cabeza manteniendo el torso estable.', 'Mover el torso en vez de aislar el movimiento en los hombros.'),
  ('kettlebell-windmill', 'Kettlebell Windmill', 'advanced', 'rotation', array['core', 'shoulders']::text[], array['hamstrings']::text[], 'Con la kettlebell bloqueada por encima de la cabeza, inclina el torso hacia el lado contrario manteniendo la vista en el peso.', 'Flexionar la rodilla de la pierna que soporta el peso en vez de mantenerla extendida.'),
  ('double-kettlebell-front-squat', 'Double Kettlebell Front Squat', 'intermediate', 'squat', array['quadriceps', 'glutes']::text[], array['core']::text[], 'Con una kettlebell en cada hombro en posición de rack, desciende manteniendo el torso vertical.', 'Dejar caer los codos, perdiendo la posición de rack.'),
  ('kettlebell-figure-8', 'Kettlebell Figure 8', 'beginner', 'rotation', array['core']::text[], array['forearms']::text[], 'Con las piernas separadas, pasa la kettlebell entre las piernas de una mano a otra dibujando un ocho.', 'Perder el ritmo del movimiento por sujetar el peso demasiado lejos del cuerpo.'),
  ('kettlebell-around-the-world', 'Kettlebell Around the World', 'beginner', 'rotation', array['core']::text[], array['forearms']::text[], 'Rota la kettlebell alrededor de la cintura pasándola de una mano a otra manteniendo el torso estable.', 'Inclinar el torso para compensar el peso en vez de mantenerlo erguido.'),
  ('band-row', 'Band Row', 'beginner', 'pull', array['back']::text[], array['biceps']::text[], 'Con la banda anclada al frente, tira de los extremos hacia la cadera contrayendo la espalda.', 'Encoger los hombros en vez de retraer las escápulas.'),
  ('band-chest-press', 'Band Chest Press', 'beginner', 'push', array['chest']::text[], array['triceps']::text[], 'Con la banda anclada detrás, empuja los extremos al frente hasta extensión completa de brazos.', 'Arquear la espalda para ganar recorrido.'),
  ('band-curl', 'Band Curl', 'beginner', 'pull', array['biceps']::text[], array['forearms']::text[], 'De pie sobre la banda, flexiona los codos elevando los extremos hasta el hombro.', 'Balancear el torso para ayudar a subir la banda.'),
  ('band-triceps-pushdown', 'Band Triceps Pushdown', 'beginner', 'push', array['triceps']::text[], array[]::text[], 'Con la banda anclada arriba, extiende los codos empujando hacia abajo sin despegarlos del torso.', 'Separar los codos del cuerpo durante la extensión.'),
  ('band-lateral-raise', 'Band Lateral Raise', 'beginner', 'push', array['shoulders']::text[], array[]::text[], 'De pie sobre la banda, eleva el brazo lateralmente hasta la altura del hombro con codo ligeramente flexionado.', 'Encoger el hombro durante la elevación.'),
  ('band-pull-apart', 'Band Pull-Apart', 'beginner', 'pull', array['shoulders', 'back']::text[], array[]::text[], 'Con los brazos extendidos al frente, separa la banda llevando los brazos hacia los lados contrayendo la espalda alta.', 'Flexionar los codos en vez de mantener los brazos extendidos.'),
  ('band-face-pull', 'Band Face Pull', 'beginner', 'pull', array['shoulders']::text[], array['back']::text[], 'Con la banda anclada a la altura de la cara, tira de los extremos hacia la cara separando los codos.', 'Tirar hacia el pecho en vez de hacia la cara.'),
  ('band-squat', 'Band Squat', 'beginner', 'squat', array['quadriceps', 'glutes']::text[], array['hamstrings']::text[], 'Con la banda sobre los hombros y anclada bajo los pies, desciende hasta muslos paralelos al suelo y sube.', 'Perder la tensión de la banda al no descender lo suficiente.'),
  ('band-good-morning', 'Band Good Morning', 'intermediate', 'hinge', array['hamstrings', 'back']::text[], array['glutes']::text[], 'Con la banda sobre los hombros y bajo los pies, inclina el torso al frente con bisagra de cadera y vuelve a subir.', 'Redondear la espalda baja en vez de mantenerla neutra.'),
  ('band-deadlift', 'Band Deadlift', 'beginner', 'hinge', array['hamstrings', 'glutes']::text[], array['back']::text[], 'De pie sobre la banda, realiza una bisagra de cadera y extiende hasta quedar completamente erguido.', 'Redondear la espalda baja durante el ascenso.'),
  ('band-overhead-press', 'Band Overhead Press', 'beginner', 'push', array['shoulders']::text[], array['triceps']::text[], 'De pie sobre la banda, empuja los extremos por encima de la cabeza hasta extensión completa.', 'Arquear la espalda baja para ayudar a completar el empuje.'),
  ('band-glute-kickback', 'Band Glute Kickback', 'beginner', 'hinge', array['glutes']::text[], array['hamstrings']::text[], 'En cuadrupedia con la banda alrededor de un pie, extiende la cadera llevando la pierna hacia atrás y arriba.', 'Arquear la espalda baja para ganar recorrido.'),
  ('cable-upright-row', 'Cable Upright Row', 'intermediate', 'pull', array['shoulders']::text[], array['back', 'forearms']::text[], 'Con la polea baja, tira de la barra verticalmente pegada al cuerpo hasta la altura del pecho.', 'Elevar el peso por encima de la altura del hombro.'),
  ('single-arm-cable-row', 'Single-Arm Cable Row', 'beginner', 'pull', array['back']::text[], array['biceps']::text[], 'Sentado con un solo agarre, tira hacia la cadera manteniendo el torso estable sin rotar.', 'Rotar el torso para ayudar a completar la tracción.'),
  ('cable-kickback', 'Cable Kickback', 'beginner', 'push', array['triceps']::text[], array[]::text[], 'Torso inclinado con la polea baja, extiende el codo llevando el agarre hacia atrás.', 'Bajar el brazo por debajo de la línea del torso durante la extensión.'),
  ('cable-face-pull', 'Cable Face Pull', 'beginner', 'pull', array['shoulders']::text[], array['back']::text[], 'Con la polea a la altura de la cara, tira de la cuerda hacia la cara separando los codos hacia fuera.', 'Tirar hacia el pecho en vez de hacia la altura de la cara.'),
  ('standing-cable-chest-press', 'Standing Cable Chest Press', 'beginner', 'push', array['chest']::text[], array['triceps', 'shoulders']::text[], 'De pie de espaldas a la polea, empuja los agarres al frente hasta extensión completa de brazos.', 'Inclinar el torso hacia delante en vez de mantenerlo estable.'),
  ('cable-hip-abduction', 'Cable Hip Abduction', 'beginner', 'squat', array['glutes']::text[], array[]::text[], 'Con el tobillo enganchado al cable, separa la pierna lateralmente manteniendo el torso estable.', 'Inclinar el torso hacia el lado contrario para ganar recorrido.'),
  ('cable-shrug', 'Cable Shrug', 'beginner', 'pull', array['back']::text[], array['forearms']::text[], 'De pie frente a la polea baja, eleva los hombros directamente hacia arriba sin flexionar el codo.', 'Rotar los hombros en vez de elevarlos en línea recta.'),
  ('assisted-pull-up-machine', 'Assisted Pull-Up Machine', 'beginner', 'pull', array['lats', 'back']::text[], array['biceps']::text[], 'De rodillas en la plataforma con contrapeso, tira hasta que la barbilla supere la barra.', 'Depender del contrapeso máximo en vez de progresar reduciéndolo con el tiempo.'),
  ('assisted-dip-machine', 'Assisted Dip Machine', 'beginner', 'push', array['chest', 'triceps']::text[], array['shoulders']::text[], 'De rodillas en la plataforma con contrapeso, desciende hasta 90° de codo y empuja de vuelta arriba.', 'Bajar en exceso comprometiendo el hombro.'),
  ('ab-crunch-machine', 'Ab Crunch Machine', 'beginner', 'core', array['core']::text[], array[]::text[], 'Sentado con el torso apoyado en el cojín, flexiona el tronco contrayendo el abdomen.', 'Tirar con los brazos en vez de flexionar con el abdomen.'),
  ('smith-machine-squat', 'Smith Machine Squat', 'beginner', 'squat', array['quadriceps', 'glutes']::text[], array['hamstrings']::text[], 'Con la barra guiada sobre los trapecios, desciende hasta muslos paralelos al suelo y empuja de vuelta.', 'Colocar los pies demasiado cerca de la trayectoria vertical de la barra.'),
  ('smith-machine-bench-press', 'Smith Machine Bench Press', 'beginner', 'push', array['chest']::text[], array['triceps', 'shoulders']::text[], 'Tumbado en el banco bajo la barra guiada, baja hasta el pecho y empuja a extensión completa.', 'Colocar el banco fuera de la trayectoria vertical de la barra.'),
  ('broad-jump', 'Broad Jump', 'intermediate', 'locomotion', array['quadriceps', 'glutes']::text[], array['calves']::text[], 'Desde parado, salta lo más lejos posible al frente aterrizando con ambos pies y control.', 'Aterrizar con las rodillas bloqueadas en vez de amortiguar flexionando.'),
  ('tuck-jump', 'Tuck Jump', 'intermediate', 'locomotion', array['quadriceps', 'glutes']::text[], array['core']::text[], 'Salta verticalmente llevando ambas rodillas hacia el pecho en el punto más alto del salto.', 'Aterrizar con poca flexión de rodilla, absorbiendo mal el impacto.'),
  ('squat-jump', 'Squat Jump', 'intermediate', 'squat', array['quadriceps', 'glutes']::text[], array['calves']::text[], 'Desde la posición baja de sentadilla, salta explosivamente hacia arriba y aterriza volviendo a la posición baja.', 'Rodillas colapsando hacia dentro en el aterrizaje.'),
  ('split-jump', 'Split Jump', 'intermediate', 'locomotion', array['quadriceps', 'glutes']::text[], array['calves']::text[], 'Desde una posición de zancada, salta alternando la pierna delantera en el aire y aterriza en zancada.', 'Aterrizar con el torso inclinado hacia delante en vez de erguido.'),
  ('depth-jump', 'Depth Jump', 'advanced', 'locomotion', array['quadriceps', 'glutes']::text[], array['calves']::text[], 'Baja de un cajón y, al tocar el suelo, salta inmediatamente lo más alto posible minimizando el tiempo de contacto.', 'Pausar demasiado en el suelo antes de saltar, perdiendo el efecto pliométrico.'),
  ('lateral-bound', 'Lateral Bound', 'intermediate', 'locomotion', array['glutes', 'quadriceps']::text[], array['calves']::text[], 'Salta lateralmente de una pierna hacia la otra amortiguando el aterrizaje con control antes de repetir.', 'Aterrizar con la rodilla colapsando hacia dentro.'),
  ('skater-jump', 'Skater Jump', 'intermediate', 'locomotion', array['glutes', 'quadriceps']::text[], array['calves']::text[], 'Salta lateralmente llevando la pierna trasera por detrás en cada aterrizaje, como el patinaje de velocidad.', 'Perder el equilibrio por aterrizar con el pie demasiado adelantado.'),
  ('plyo-push-up', 'Plyo Push Up', 'advanced', 'push', array['chest', 'shoulders']::text[], array['triceps', 'core']::text[], 'Empuja con fuerza suficiente para que las manos despeguen del suelo y aterriza amortiguando con los codos.', 'Aterrizar con los codos completamente bloqueados en vez de amortiguar.'),
  ('box-step-down', 'Box Step-Down', 'beginner', 'locomotion', array['quadriceps', 'glutes']::text[], array['calves']::text[], 'De pie sobre el cajón, desciende con una pierna con control hasta tocar el suelo con el talón.', 'Dejarse caer sin control en vez de bajar de forma controlada.'),
  ('single-leg-box-jump', 'Single-Leg Box Jump', 'advanced', 'locomotion', array['quadriceps', 'glutes']::text[], array['calves', 'core']::text[], 'Desde apoyo en una sola pierna, salta al cajón aterrizando con la misma pierna con control.', 'Usar impulso excesivo del brazo contrario en vez de fuerza de la pierna.')
on conflict (slug) do nothing;

-- Equipment links --------------------------------------------------------
insert into public.exercise_equipment (exercise_id, equipment_slug)
select e.id, x.equipment_slug
from (values
  ('decline-barbell-bench-press', 'barbell'),
  ('decline-barbell-bench-press', 'bench'),
  ('decline-dumbbell-press', 'dumbbells'),
  ('decline-dumbbell-press', 'bench'),
  ('incline-dumbbell-press', 'dumbbells'),
  ('incline-dumbbell-press', 'bench'),
  ('close-grip-bench-press', 'barbell'),
  ('close-grip-bench-press', 'bench'),
  ('svend-press', 'plate'),
  ('floor-press', 'barbell'),
  ('dumbbell-fly', 'dumbbells'),
  ('dumbbell-fly', 'bench'),
  ('incline-dumbbell-fly', 'dumbbells'),
  ('incline-dumbbell-fly', 'bench'),
  ('cable-fly-low-to-high', 'cable_machine'),
  ('cable-fly-high-to-low', 'cable_machine'),
  ('chest-press-machine', 'gym_machine'),
  ('pec-deck', 'gym_machine'),
  ('decline-push-up', 'bench'),
  ('seated-cable-row', 'cable_machine'),
  ('single-arm-dumbbell-row', 'dumbbells'),
  ('single-arm-dumbbell-row', 'bench'),
  ('chest-supported-row', 'dumbbells'),
  ('chest-supported-row', 'bench'),
  ('t-bar-row', 'barbell'),
  ('machine-row', 'gym_machine'),
  ('straight-arm-pulldown', 'cable_machine'),
  ('dumbbell-pullover', 'dumbbells'),
  ('dumbbell-pullover', 'bench'),
  ('wide-grip-lat-pulldown', 'cable_machine'),
  ('close-grip-lat-pulldown', 'cable_machine'),
  ('barbell-shrug', 'barbell'),
  ('dumbbell-shrug', 'dumbbells'),
  ('good-morning', 'barbell'),
  ('landmine-row', 'barbell'),
  ('renegade-row', 'dumbbells'),
  ('rack-pull', 'barbell'),
  ('sumo-deadlift', 'barbell'),
  ('arnold-press', 'dumbbells'),
  ('seated-dumbbell-shoulder-press', 'dumbbells'),
  ('seated-dumbbell-shoulder-press', 'bench'),
  ('machine-shoulder-press', 'gym_machine'),
  ('upright-row', 'barbell'),
  ('cable-lateral-raise', 'cable_machine'),
  ('cable-front-raise', 'cable_machine'),
  ('reverse-fly-machine', 'gym_machine'),
  ('dumbbell-reverse-fly', 'dumbbells'),
  ('plate-front-raise', 'plate'),
  ('cuban-press', 'dumbbells'),
  ('barbell-curl', 'barbell'),
  ('ez-bar-curl', 'barbell'),
  ('dumbbell-curl', 'dumbbells'),
  ('hammer-curl', 'dumbbells'),
  ('incline-dumbbell-curl', 'dumbbells'),
  ('incline-dumbbell-curl', 'bench'),
  ('preacher-curl', 'barbell'),
  ('preacher-curl', 'bench'),
  ('concentration-curl', 'dumbbells'),
  ('cable-curl', 'cable_machine'),
  ('reverse-curl', 'barbell'),
  ('drag-curl', 'barbell'),
  ('triceps-pushdown', 'cable_machine'),
  ('overhead-triceps-extension', 'dumbbells'),
  ('skull-crusher', 'barbell'),
  ('skull-crusher', 'bench'),
  ('cable-overhead-extension', 'cable_machine'),
  ('dumbbell-kickback', 'dumbbells'),
  ('dumbbell-kickback', 'bench'),
  ('machine-triceps-extension', 'gym_machine'),
  ('wrist-curl', 'dumbbells'),
  ('hack-squat', 'gym_machine'),
  ('sumo-squat', 'dumbbells'),
  ('single-leg-leg-press', 'gym_machine'),
  ('adductor-machine', 'gym_machine'),
  ('abductor-machine', 'gym_machine'),
  ('stiff-leg-deadlift', 'barbell'),
  ('single-leg-romanian-deadlift', 'dumbbells'),
  ('deficit-deadlift', 'barbell'),
  ('cable-pull-through', 'cable_machine'),
  ('cable-glute-kickback', 'cable_machine'),
  ('seated-calf-raise', 'gym_machine'),
  ('leg-press-calf-raise', 'gym_machine'),
  ('donkey-calf-raise', 'gym_machine'),
  ('jefferson-curl', 'plate'),
  ('banded-hip-abduction', 'resistance_band'),
  ('monster-walk', 'resistance_band'),
  ('dead-bug', 'mat'),
  ('bird-dog', 'mat'),
  ('ab-wheel-rollout', 'ab_wheel'),
  ('cable-crunch', 'cable_machine'),
  ('reverse-crunch', 'mat'),
  ('bicycle-crunch', 'mat'),
  ('pallof-press', 'cable_machine'),
  ('band-pallof-press', 'resistance_band'),
  ('woodchopper', 'cable_machine'),
  ('dragon-flag', 'bench'),
  ('knee-tuck', 'bench'),
  ('wide-grip-pull-up', 'pull_up_bar'),
  ('neutral-grip-pull-up', 'pull_up_bar'),
  ('commando-pull-up', 'pull_up_bar'),
  ('archer-pull-up', 'pull_up_bar'),
  ('typewriter-pull-up', 'pull_up_bar'),
  ('one-arm-pull-up-progression', 'pull_up_bar'),
  ('l-sit-pull-up', 'pull_up_bar'),
  ('ring-dip', 'suspension_trainer'),
  ('weighted-dip', 'parallel_bars'),
  ('front-lever-tuck', 'pull_up_bar'),
  ('front-lever', 'pull_up_bar'),
  ('back-lever-tuck', 'pull_up_bar'),
  ('human-flag', 'pull_up_bar'),
  ('kettlebell-clean', 'kettlebell'),
  ('kettlebell-press', 'kettlebell'),
  ('single-arm-kettlebell-press', 'kettlebell'),
  ('kettlebell-row', 'kettlebell'),
  ('kettlebell-goblet-lunge', 'kettlebell'),
  ('kettlebell-halo', 'kettlebell'),
  ('kettlebell-windmill', 'kettlebell'),
  ('double-kettlebell-front-squat', 'kettlebell'),
  ('kettlebell-figure-8', 'kettlebell'),
  ('kettlebell-around-the-world', 'kettlebell'),
  ('band-row', 'resistance_band'),
  ('band-chest-press', 'resistance_band'),
  ('band-curl', 'resistance_band'),
  ('band-triceps-pushdown', 'resistance_band'),
  ('band-lateral-raise', 'resistance_band'),
  ('band-pull-apart', 'resistance_band'),
  ('band-face-pull', 'resistance_band'),
  ('band-squat', 'resistance_band'),
  ('band-good-morning', 'resistance_band'),
  ('band-deadlift', 'resistance_band'),
  ('band-overhead-press', 'resistance_band'),
  ('band-glute-kickback', 'resistance_band'),
  ('cable-upright-row', 'cable_machine'),
  ('single-arm-cable-row', 'cable_machine'),
  ('cable-kickback', 'cable_machine'),
  ('cable-face-pull', 'cable_machine'),
  ('standing-cable-chest-press', 'cable_machine'),
  ('cable-hip-abduction', 'cable_machine'),
  ('cable-shrug', 'cable_machine'),
  ('assisted-pull-up-machine', 'gym_machine'),
  ('assisted-dip-machine', 'gym_machine'),
  ('ab-crunch-machine', 'gym_machine'),
  ('smith-machine-squat', 'gym_machine'),
  ('smith-machine-bench-press', 'gym_machine'),
  ('smith-machine-bench-press', 'bench'),
  ('depth-jump', 'box'),
  ('box-step-down', 'box'),
  ('single-leg-box-jump', 'box')
) as x(exercise_slug, equipment_slug)
join public.exercises e on e.slug = x.exercise_slug
on conflict (exercise_id, equipment_slug) do nothing;
